### ISSUE TITLE
Pod install fails swift 4

### ISSUE THREAD

**Issue by XcOdeTanzania** [GEOSwift/GEOSwift#107]
Error:
Installing geos (3.5.0)
[!] /bin/bash -c 
set -e
type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

sed -i "" "s/\/\* #undef HAVE_INT64_T_64 \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h
sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\* #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h

cat <<EOT >> include/geos/platform.h
  #undef ISNAN
  #define ISNAN(x) (std::isnan(x))
EOT

patch capi/geos_c.h <<EOF
  149c149
  < #include <geos/export.h>
  ---
  > #define GEOS_DLL
EOF

/bin/bash: line 2: alias: autoconf: not found
/bin/bash: line 2: alias: xcrun autoconf: not found

................My pod file.........
platform :ios, '10.0'

target 'mySpot' do
    use_frameworks!
    
    # Pods for mySpot
    pod 'SVProgressHUD'
    pod 'ChameleonFramework'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'lottie-ios'
    pod 'Mapbox-iOS-SDK', '~> 4.1'
    pod 'TransportApiSdk', :git => 'https://github.com/XcOdeTanzania/TransportApiSdk.iOS.git', :commit => 'b65ce4b459e1d1ffa3e6cfe1eb7fa987dbf7fdf2'
    pod 'GEOSwift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end

**Comment by macdrevx** [comment]
Hi @XcOdeTanzania, the line `/bin/bash: line 2: alias: autoconf: not found` in the output suggests to me that you need to make sure you have a few dependencies installed. If you use Homebrew, you can run: `brew install autoconf automake libtool`. After that, try running `pod install` again. Let us know if this doesn't work.

**Comment by XcOdeTanzania** [comment]
Thanks, it worked like a charm.
