### ISSUE TITLE
envelope() makes incorrect geometry type assumption, resulting in crash

### ISSUE THREAD

**Issue by macdrevx** [GEOSwift/GEOSwift#108]
This is happening on develop (has not been released to cocoapods yet). We should definitely fix it before the next release.

```
import XCTest
@testable import GEOSwift
import geos

final class SpatialAnalysisTests: XCTestCase {
    func test() {
        guard let envelope = Waypoint(latitude: 1, longitude: 1)!.envelope() else {
            XCTFail("Failed to create envelope")
            return
        }

        // envelope is type Envelope, which is a subclass of Polygon

        // Actual geometry type is GEOS_POINT (0)
        print(GEOSGeomTypeId_r(GEOS_HANDLE, envelope.storage.GEOSGeom))

        // Crashes because the input to GEOSGetExteriorRing_r must be of type GEOS_POLYGON:
        _ = envelope.exteriorRing
    }
}
```

To fix this, we should revert the change to the return type of `envelope()` (was `Geometry`, is now `Envelope`). We may also want to eliminate the `Envelope` subclass of `Polygon`. Is there any reason its methods can't just be added to `Polygon` directly?

**Comment by macdrevx** [comment]
@samritchie can you weigh in on this?

**Comment by samritchie** [comment]
Yes, I’ve also noticed points & some other geometries don’t return a polygon from envelope. I’d suggest either manufacturing one with appropriate coords or return an optional. I can have a look at this, but not today, I’m flat out at the moment.
