### ISSUE TITLE
MultiPolygon mapShape crash

### ISSUE THREAD

**Issue by vfn** [GEOSwift/GEOSwift#11]
When attempting to generate a shape from a MultiPolygon instance, the following crash happens in the switch's default case:

```
Could not cast value of type 'GEOSwift.MultiPolygon<GEOSwift.Polygon>' (0x11e22d030) to 'GEOSwift.GeometryCollection<GEOSwift.Geometry>' (0x11e22c230).
```

The commit https://github.com/Homely/GEOSwift/commit/13988a13d6a396a0f0d44cdb2904f2cff61c1c92 fixes the problem. Unfortunately I could not find a way to handle that on a generic fashion. I'm happy to change the code if a better solution exists.

A test multipolygon can be found at: https://gist.github.com/vfn/6c932835dee0ae3f2111#file-multipoligon-wkt

**Comment by andreacremaschi** [comment]
Hi @vfn and thank you! :beer: 
 
`MultiPolygon` is a subclass of `GeometryCollection`, so it is not clear to me why `GEOSwift.MultiPolygon<GEOSwift.Polygon>` can't be cast to `GEOSwift.GeometryCollection<GEOSwift.Geometry>`. I suppose it has something to do with generics. 
I prefer to wait a bit before merging your PR, as it would not solve the issue for geometry collections with mixed geometry type (es a waypoint and a linestring) and I would like to keep track of the issue. 

A possible workaround may be to add a `case let gc as GeometryCollection<Geometry>`, have you tried? But still I'd prefer to create a `Multipolygon` when the WKT is so specific..

**Comment by vfn** [comment]
@andreacremaschi I don't understand why it cannot infer the type and also fails on casting to GeometryCollection<Geometry>.

I did try what you suggested, but the default case is triggered instead of:
```Swift
case let gc as GeometryCollection<Geometry>:
            return MKShapesCollection(geometryCollection: gc)
```

Regarding the PR, there are a few other tweaks there that you might want to merge or cherry pick. (e.g.: https://github.com/Homely/GEOSwift/commit/693601d357b2970cf92be5c002c15c35e82d7717)

**Comment by andreacremaschi** [comment]
Ah ok, thank you. I decided to merge the PR, and look at this ASAP

**Comment by macdrevx** [comment]
@raugturi and I ran into this issue when refactoring a while ago (and reintroduced the bug). The reason it doesn’t work is that swift generics are invariant.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by macdrevx** [comment]
See diff in #125 for more info.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
