### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by egorf** [GEOSwift/GEOSwift#116]
Hey guys!

First of all, this is a really cool project. It's lovely to see well integrated Swift libraries, great job.

Secondly, I have a small question regarding the licensing. GEOSwift is MIT licensed, which is really nice. However, it is based on GEOS, which is LGPL. Does this mean that if I want to use GEOSwift in my iOS application, I effectively have to make it open source? Or is the actual situation different?

Thanks in advance.

**Comment by macdrevx** [comment]
@egorf good question, but probably not one that is best answered here. You'll find many discussions of this topic if you search "iOS LGPL". You may also want to reach out to the GEOS team and seek your own legal counsel.
