### ISSUE TITLE
Objective-C compatibility

### ISSUE THREAD

**Issue by alexisbar** [GEOSwift/GEOSwift#119]
Hello, 

I updated my pod today to 3.0.0 in my projects. 
They are made in Objective-C. Since the update, all my methods using GEOSwift from ObjC are returning an error at compilation. For example the Geometry.create method or the WKT property of the Waypoint object. 
It seems that if I add the @objc prefix in the create method this resolve the issue. 

Do you have a better solution ? I can fix my errors and submit a pull request if you want.

**Comment by macdrevx** [comment]
@alexisbar thanks for reporting this. Feel free to submit a PR to the develop branch. I think your suggestion sounds reasonable.

**Comment by macdrevx** [comment]
@alexisbar 3.0.1 is now available on CocoaPods with your changes. Thanks for the fix!
