### ISSUE TITLE
Error trying to install earlier version of geos

### ISSUE THREAD

**Issue by joeuelk** [GEOSwift/GEOSwift#123]
What's the best way to install an earlier version of GEOSwift and geos using cocoapods? The latest geos version 3.7 won't compile due to a missing `geos/platform.h` file.

I tried updating the Podfile to earlier versions I know work:

```
pod 'GEOSwift', '~> 2.2.0'
pod 'geos', '~> 3.5.0'
```

But I get the following errors.
```
[!] Error installing geos
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force https://svn.osgeo.org/geos/tags/3.5.0 /var/folders/0x/b8pbfqnn0qs_fr2cz2kp_f4h0000gn/T/d20181013-17539-1nd0bf1

svn: E170013: Unable to connect to a repository at URL 'https://svn.osgeo.org/geos/tags/3.5.0'
svn: E175013: Access to '/geos/tags/3.5.0' forbidden
```

Thanks

**Comment by macdrevx** [comment]
Looks like the SVN repo that the old version pulled from has been disabled. I'll reach out to them to see if they can reenable it. I'd also like to fix the install issue in geos 3.7.0. Can you provide more details?

**Comment by macdrevx** [comment]
Here's the relevant ticket on GEOS: https://trac.osgeo.org/geos/ticket/934

I've requested a login so that I can ask about it.

**Comment by macdrevx** [comment]
To restore access to 3.5.0, we may need to republish it and point it to git.

Replacing already-published podspecs: https://stackoverflow.com/questions/25604601/how-to-do-pod-trunk-push-to-replace-an-existing-version-of-podspec/44317506#44317506

3.5.0 on git: https://git.osgeo.org/gitea/geos/geos/src/tag/3.5.0

**Comment by macdrevx** [comment]
@joeuelk I've republished 3.5.0 so that it points to the GEOS git repo and builds similarly to how we're building 3.7.0. It should be very similar to how the old 3.5.0 worked. Can you give it a try and let me know how it turns out?

**Comment by joeuelk** [comment]
Looks like it installs now. Thank you!

Still having trouble getting my project to build but I'm not clear it's related to geos now.

**Comment by macdrevx** [comment]
Glad to hear it. I'll close this issue, but please let us know if you find other geos/GEOSwift issues.
