### ISSUE TITLE
mapShape returns nil for MultiPolygon

### ISSUE THREAD

**Issue by ashachakrapani** [GEOSwift/GEOSwift#124]
With the latest GeoSwift pod, mapShape returns nil for a well-formatted MultiPolygon
The switch case in MapKit.swift throws an error when I po in debug mode - i.e. 'case let gc as GeometryCollection<Geometry>:' . The error I see is 'Could not cast value of type 'GEOSwift.MultiPolygon<GEOSwift.Polygon>' (0x7fd7b99baf78) to 'GEOSwift.GeometryCollection<GEOSwift.Geometry>' (0x7fd7bb0f6240)'. It does not crash the app or log on console though. Just skips the cases when the geoJSON represents a MultiPolygon and returns nil.

The GeoJSON I am using is valid (validated in GeoJSONLint) and it used to render the shape until a recent pod update. 
Attached is the GeoJSON I am referring to. 
[multipolygon.txt](https://github.com/GEOSwift/GEOSwift/files/2479220/multipolygon.txt)

Casting as below appears to work but not as a generic geometry
case is GeometryCollection<Polygon>:
            return MKShapesCollection(geometryCollection: self as! GeometryCollection<Polygon>)

Would you be able to confirm why?

**Comment by macdrevx** [comment]
Thanks for the bug report @ashachakrapani. I'll take a look and get back to you ASAP.

**Comment by macdrevx** [comment]
@ashachakrapani I've opened a pull request with a fix for this issue. Take a look if you have a chance and let us know what you think.

**Comment by ashachakrapani** [comment]
@macdrevx Swift generics being invariant explains why it worked when I casted it to a specific type of shape which is how we made a temporary fix in our fork too. Thanks for looking into it promptly.

**Comment by macdrevx** [comment]
We'll get it reviewed and merged soon

**Comment by macdrevx** [comment]
(and released)

**Comment by macdrevx** [comment]
@ashachakrapani I just released 3.0.2 with the fix for this issue. Thanks for reporting it!
