### ISSUE TITLE
Any way to make good polygons from dirty data?

### ISSUE THREAD

**Issue by ssokol** [GEOSwift/GEOSwift#130]
This is really an issue of dirty data rather than anything to do with GEOSwift, but...

I have an application that uses data provided by the FAA. It includes, among other things, various airspaces (sections of the sky) that are allocated for use by the military. My application draws those spaces on a moving map, helping pilots of recreational aircraft avoid unwanted interactions with mlitary aircraft.

Most of the data is good, but I have a few items that arrive in an XML format that apparently does not require the last point in a polygon match the first point in the polygon. That data gets converted in Spatialite, then gets extracted as GeoJSON text which gets serialized into a dictionary and then turned into a geometry object:

```
    func convertToDictionary(text: String) -> [String: Any]? {
        if let data = text.data(using: .utf8) {
            do {
                return try JSONSerialization.jsonObject(with: data, options: []) as? [String: Any]
            } catch {
                return nil
            }
        }
        return nil
    }

    func getGeometries(json:String) -> [Geometry]? {
            if let dictionary = self.convertToDictionary(text: json) {
                if let geometries = Geometry.fromGeoJSONDictionary(dictionary as Dictionary<String, AnyObject>) {
                  return geometries
                }
            }
            return nil
    }
```

When this gets one of the JSON strings with an unclosed polygon, it fails. Understandable - the data doesn't conform to the GeoJSON rules. This results in lots of this:

```
14:28:42.584 - No geometries for MAXWELL 1 MOA, CA
GEOSwift # IllegalArgumentException: Points of LinearRing do not form a closed linestring.
GEOSwift # Shell is not a LinearRing.
```

So my question: is there any way to get GeoSwift / GEOS to automagically close unclosed polygons, or am I going to have to scrub the data manually?

**Comment by macdrevx** [comment]
Hi @ssokol. This problem seems specific to your use case, so I think scrubbing the data before you feed it into GEOSwift makes sense to me. I’m going to close this issue for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
