### ISSUE TITLE
fatal error: 'geos/platform.h' file not found

### ISSUE THREAD

**Issue by nylemusgrave** [GEOSwift/GEOSwift#132]
@macdrevx I'm getting the platform.h file not found error again in my build server. I can't find anything that has changed on our side...did something perhaps change with the repo??

```
/Users/vsts/agent/2.144.0/work/1/s/LandDB_iOS_Mobile/Pods/geos/geos/include/geos/geom/Coordinate.h:19:10: fatal error: 'geos/platform.h' file not found
#include <geos/platform.h> // for DoubleNotANumber
         ^~~~~~~~~~~~~~~~~
1 error generated.

** ARCHIVE FAILED **
```

Our build server rebuilds everything from scratch each time, we run the commands below to ensure that any cache is cleared which had caused the issue before...but now the scripts just never seem to install platform.h ever.
[logs_876 (1).zip](https://github.com/GEOSwift/GEOSwift/files/2746204/logs_876.1.zip)

```
brew install autoconf automake libtool

pod cache list geos
pod cache clean geos --all
```

I run the commands above every build, was working but now I'm getting the error when archiving even tho there is no cache found to clear.

**Comment by macdrevx** [comment]
Hi @nylemusgrave thanks for opening a new issue. I’d like to gather some more information to help us identify what’s going wrong. Can you please share your Podfile.lock and the output of running `pod install --verbose` on your build server? Also, which version of CocoaPods are you using?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nylemusgrave** [comment]
@macdrevx 

Podlock and Log of the verbose insall attached.


[podlock.txt](https://github.com/GEOSwift/GEOSwift/files/2746734/podlock.txt)
[podInstallVerbose.txt](https://github.com/GEOSwift/GEOSwift/files/2746739/podInstallVerbose.txt)

**Comment by macdrevx** [comment]
Thanks for that extra info. It doesn't quite tell me everything I need to know to identify the problem, so can you try another diagnostic test and share the results? Run this on your build server after the `brew install` step and share the output here so we can look for errors:

```
git clone https://github.com/GEOSwift/geos.git
cd geos
sh prepare.sh
```

**Comment by nylemusgrave** [comment]
@macdrevx Ended up being an issue with brew, it was throwing an error on the brew install where it was having an issue updating the version.

Adding `brew update` prior to the install call fixed it.

**Comment by macdrevx** [comment]
@nylemusgrave glad you we able to get it working again!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sauvikated** [comment]
https://github.com/andreacremaschi/SpatialDBKit/issues/24#issuecomment-473840018

**Comment by dandyweng** [comment]
`pod "GEOSwift", "= 3.0.1"` works! Guess I'll have to settle with this old version for now.
