### ISSUE TITLE
Provide buffer width in meters to LineString?

### ISSUE THREAD

**Issue by rdaly1490** [GEOSwift/GEOSwift#140]
Is there currently a way to create a buffered LineString, which has a buffer width defined in meters instead of decimal degrees?

**Comment by macdrevx** [comment]
Prior to v5, we assumed that the units of our coordinate system were in degrees lat/lon, but that assumption has been removed in v5 (unless you're also using the GEOSwift+MapKit add-on).

Version 5 has `func buffer(by width: Double) throws -> Geometry`, so if the rest of your geometry is represented in meters, then you can pass meters to buffer. In the end, it's just doing 2D geometry, so it's up to you to define what what units you're using.

If you do choose to use degrees lat/lon as your base units, you'd need to also pass degrees into buffer.
