### ISSUE TITLE
Release 3.1.0 compile issue

### ISSUE THREAD

**Issue by borut-t** [GEOSwift/GEOSwift#141]
Trying to compile project against version `3.1.0` generates compile time issue:
```
/Pods/geos/geos/include/geos/geom/Coordinate.h:19:10: 'geos/platform.h' file not found
```

**Comment by macdrevx** [comment]
Hi @borut-t, usually this happens when something goes wrong with `autotools` during `pod install`. The first thing I'd check is to make sure that `autoconf`, `automake`, and `libtool` are all installed.

**Comment by borut-t** [comment]
`libtool` is installed, the other two are not. How do I install them and why do I need to do that? I've been using cocoapods since forever and never needed to install it.

**Comment by macdrevx** [comment]
You can install all 3 with homebrew: `brew install autoconf automake libtool`. The reason you need them is specific to this library — not cocoapods. GEOSwift is a wrapper around the geos library, which is built with these tools during a custom setup script that hooks into `pod install`.

**Comment by cado1982** [comment]
I just stumbled across this problem. I failed to read the instructions to run `brew install autoconf automake libtool`. If you don't have those tools and try to install GEOSwift Cocoapods will cache the unbuilt geos pod and use it even after you try to `pod install`. You can verify this by running `pod install --verbose` and checking the output.

To solve that you can clear the cache and then rerun pod install.

- Remove `pod GEOSwift` from your podfile
- Run `pod install` to remove GEOSwift and geos from your project
- Run `pod cache clean 'geos' --all` and `pod cache clean 'GEOSwift' --all`
- Add `pod GEOSwift` back to your podfile
- Run `pod install --verbose` and check that prepare.sh is being run in the output

**Comment by macdrevx** [comment]
Thanks @cado1982. I wouldn't be surprised if a slimmed down version of those instructions would work too:

* Run `pod cache clean 'geos' --all`
* Run `pod install --verbose` and check that prepare.sh is being run in the output

In other words, no need to remove/readd the pod from your podfile.

**Comment by borut-t** [comment]
I was able to update it successfully after following @cado1982 steps.
