### ISSUE TITLE
Creating Geometry Of Incorrect Type Leaks

### ISSUE THREAD

**Issue by trevor-thoele** [GEOSwift/GEOSwift#146]
Creating a geometry from WKT/WKB/Data causes a leak as the geometry that is created is never deleted when early returning from the initializer.

`Polygon(WKT: "POINT(30 10)")` is enough to leak.

**Comment by trevor-thoele** [comment]
By the way, I

**Comment by trevor-thoele** [comment]
Opened PR for this.
https://github.com/GEOSwift/GEOSwift/pull/147

**Comment by macdrevx** [comment]
Merged into develop. Thanks @trevor-thoele
