### ISSUE TITLE
Issue converting buffered linestring into mapshape (bug?)

### ISSUE THREAD

**Issue by alexahlen** [GEOSwift/GEOSwift#150]
Im getting an error when i convert a buffered linestring into a mapshape. My code works perfectly up until that point, and the WKT seems formatted the correct way. I assume its an issue on my end, but if someone could have a quick flick through it might be a bug?

here is a longer explanation:
https://stackoverflow.com/questions/55600134/why-is-my-linestring-not-converting-to-mapshape-in-geoswift-only-happens-with

also some links to see what is being returned (also linked in stackoverflow)

Both of these are being produced when the error does occur (so you can see the WKT string is working):
LineString: https://imgur.com/a/7OLPZkM
Buffered LineString: https://imgur.com/a/KJRfpRX

the reason i wonder if it is a bug is that if you look at the buffered linestring it doesnt seem to be a closed ring, i thought this might be causing an issue in converting it to mapshape?

If anyone has any thoughts on this, please let me know.

**Comment by macdrevx** [comment]
Hi @alexahlen, can you please share the input data that results in the error? Also, there's a new version of GEOSwift out now (v5 - migration guide [here](https://github.com/GEOSwift/GEOSwift/blob/master/VERSION_5.md)). I'd be interested whether this issue still happens on that version.

**Comment by macdrevx** [comment]
Hi @alexahlen, since we haven’t heard back from you, I’m going to close this issue. If you are still having the same error with v5 and can provide more info, feel free to reopen it
