### ISSUE TITLE
How can I get the Point List or Polygon Object by a LineString.buffer() in GEOSwift?

### ISSUE THREAD

**Issue by zhuyuping** [GEOSwift/GEOSwift#158]
In MKMapView, I want to detected the Tap Action in whitch side(line) of a Polygon. MKMapView Instance may have only One Polygon. So here's my idea is that compute every side of the polygon to a little polygon by buffer method of LineString Instance in GEOSwift Framework.It means that every two points convert to a rentangle Ploygon.When user touched(Tap),checked the touch point if one little polyon is contained. In this way, it can compute which side of the big Polygon touch by user. However,I can get the Points of LineString.buffer(),so i can not make a little polygon. have any other method can solve my Problem ths~~

link here : https://stackoverflow.com/questions/56140939/how-can-i-get-the-point-list-or-polygon-object-by-a-linestring-buffer-in-geosw

**Comment by macdrevx** [comment]
You could do something like this:

        let line = LineString(points: [Coordinate(x: 1, y: 0), Coordinate(x: 1, y: 10)])!
        let bufferedLine = line.buffer(width: 1)
        let polygon = bufferedLine as! Polygon
        let points = polygon.exteriorRing.points

Note that the resulting polygon has rounded end caps. GEOS supports different end cap styles, but that functionality isn't exposed in GEOSwift right now.

**Comment by macdrevx** [comment]
Since I haven't heard back, I'm going to assume this answered your question. Feel free to reopen this issue if that's not the case.
