### ISSUE TITLE
Converting from Geometry to GeoJSON

### ISSUE THREAD

**Issue by ParankushBhardwaj** [GEOSwift/GEOSwift#162]
There's no default way to convert a Geometry object back to a GeoJSON file in this wrapper. I'm attempting to make one myself and was wondering if there's a default way to get the array of coordinates from a particular shape?

**Comment by macdrevx** [comment]
@ParankushBhardwaj I'm actually working on a major update to this library that add this functionality via Codable. If you'd like to give it a try, I'd be happy to hear your feedback. Check out the branch: https://github.com/GEOSwift/GEOSwift/tree/feature/version-5-rewrite

**Comment by funkenstrahlen** [comment]
@macdrevx iOS 13 contains Codable support for GEOJson to some extend. You might want to take a look at this.

Currently it does only support decoding though: https://developer.apple.com/documentation/mapkit/mkgeojsondecoder#

**Comment by macdrevx** [comment]
Thanks for the tip!

**Comment by macdrevx** [comment]
Version 5 is up for review: #167 

Please let me know if you have any feedback.

**Comment by macdrevx** [comment]
Version 5 is now available.

**Comment by aahsanali** [comment]
@ParankushBhardwaj , I am also using GeoSwift in one of my projects can you please guide how to get points back from geometry?
Thanks

**Comment by macdrevx** [comment]
Hi @aahsanali, I'll answer this in #177

**Comment by aahsanali** [comment]
@macdrevx , thanks :)
