### ISSUE TITLE
Add SPM support for iOS and tvOS

### ISSUE THREAD

**Issue by funkenstrahlen** [GEOSwift/GEOSwift#166]
I tried using `GEOSwift` via Swift Package Manager. I therefore installed `geos` via homebrew and confirmed `pkg-config --validate geos_c` resolves successfully by copying `geos_c.pc` to the correct location.

The app builds fine in Xcode but when I try to launch it I get an error:

```
dyld: Library not loaded: /usr/local/opt/geos/lib/libgeos_c.1.dylib
  Referenced from: /Users/stefan/Library/Developer/CoreSimulator/Devices/D040B4EF-33DF-438D-B789-E9C8D083B2D8/data/Containers/Bundle/Application/2182F935-0346-4B00-A039-30AFF1762431/Pollenflug.app/Pollenflug
  Reason: no suitable image found.  Did find:
	/usr/local/opt/geos/lib/libgeos_c.1.dylib: mach-o, but not built for iOS simulator
```

I could not find any resources on how to deal with this kind of error. Any ideas?

**Comment by macdrevx** [comment]
Can you please share which version of GEOSwift you’re using and which platform your building for?

**Comment by funkenstrahlen** [comment]
@macdrevx Of course!

**Comment by macdrevx** [comment]
I think the problem is that our SPM setup only works for Mac and Linux. We’ll need to update it to work for with iOS/tvOS and Xcode 11.

**Comment by funkenstrahlen** [comment]
I understand. Anything I can do to help?

**Comment by macdrevx** [comment]
Since there are geos packages available through homebrew and apt, we've just been relying on those for mac/linux. For iOS (via CocoaPods & Carthage) we build geos ourselves (see https://github.com/GEOSwift/geos). So I think step 1 is to update https://github.com/GEOSwift/geos to support SPM. You're welcome to give that a try and open a PR. Please keep in mind that any changes we make need to preserve support for Xcode 10 at least for a little while.

**Comment by macdrevx** [comment]
Whenever we do this, I'd like to see us stop depending on the homebrew- and apt-distributed geos packages and instead always depend on our own SPM-based geos package. This should provide a higher level of consistency between CocoaPods, Carthage, and SPM and will also be necessary for new features we want to add that will require geos 3.8.0 like #157

**Comment by macdrevx** [comment]
Available in v6
