### ISSUE TITLE
How can I get a collection of points more conveniently?

### ISSUE THREAD

**Issue by zhuyuping** [GEOSwift/GEOSwift#170]
In most cases, we just need to use the GEOVSwift framework to calculate the relationship of geometry.
For example, I have a collection of several points. I want to calculate the point set corresponding to the buffer() value. I call the buffer method to calculate a Geometry object. I need to get all the points of this object. It seems that only WKT is a way. Is there any other way to get the [Coordinate] array? Or is there a convenient way to parse a WKT string into an array of objects?

**Comment by macdrevx** [comment]
Hi @zhuyuping. Which version of GEOSwift are you using?

**Comment by zhuyuping** [comment]
my Project is using Swift 4.2 , the version of GEOSwift is 4.1.0

**Comment by macdrevx** [comment]
I don't know that there's a "convenient" way to do this in 4.1.0. What should work is to test which [subclass of Geometry](https://github.com/GEOSwift/GEOSwift/blob/4.1.0/GEOSwift/Geometries.swift) you receive and then add logic to extract the coordinates.

Here's a start to how it might look:

```
switch geometry {
case is Waypoint:
    let point = geometry as! Waypoint
    let coordinate = point.coordinate
case is Polygon:
    let polygon = geometry as! Polygon
    let coordinates = Array(polygon.exteriorRing.points)
case is LineString:
    ...
}
```

**Comment by zhuyuping** [comment]
Thank you for your answer

`public extension Geometry {
    func getCoordinates() -> [Coordinate] {
        switch self {
        case is Waypoint:
            let point = self as! Waypoint
            let coordinate = point.coordinate
            return [coordinate]
        case is LineString:
            let line = self as! LineString
            let coordinates = Array(line.points)
            return coordinates
        case is LinearRing:
            let linearRing = self as! LinearRing
            let coordinates = Array(linearRing.points)
            return coordinates
        case is Polygon:
            let polygon = self as! Polygon
            let coordinates = Array(polygon.exteriorRing.points)
            return coordinates
        default:
            return []
        }
}`

**Comment by aahsanali** [comment]
@macdrevx, @zhuyuping  How can we achieve same functionality in v5.0

**Comment by macdrevx** [comment]
Hi @aahsanali, I'll answer this in #177
