### ISSUE TITLE
How can I use isSimple() method?

### ISSUE THREAD

**Issue by zhuyuping** [GEOSwift/GEOSwift#172]
- question 1:

I am using version 4.1.0, Swift 4.2

I hope I can use this method： isSimple. to judge a polygon

As I understand it, I added a method in extension Geometry:

```
// in SpatialAnalysis.swift file
public extension Geometry {
  func isSimple() -> Bool {
        let result =  GEOSisSimple_r(GEOS_HANDLE, self.storage.GEOSGeom)
        assert(result != 2, "GEOSisSimple_r on exception")
        return result == 1
    }
}
```

but alway return true，Can you give me some advice?

In addition, The problem may be：
```
// in Polygon.cpp file

bool
Polygon::isSimple() const
{
	return true;
}
```

 - question 2:

I hope to contribute to this project. Is there any step?

**Comment by zhuyuping** [comment]
isSimple for test 
```
func testSimpleGeosmetry() {
        let polygonWKT = "POLYGON((0 0, 10 10, 10 0, 0 10, 0 0))"
        let polygon = Polygon(WKT: polygonWKT)!
        let result = polygon.isSimple()
        XCTAssertTrue(result)
    }
```

**Comment by macdrevx** [comment]
Here are some docs on isSimple from JTS (the library geos is based on): https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/IsSimpleOp.html

To add this to the library, take a look at [GeometryConvertible+GEOS.swift](https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/GEOS/GeometryConvertible%2BGEOS.swift).

There are examples of binary predicates that you could use as a guide to integrate isSimple, which would be our first unary predicate.

Please be sure to branch off of develop and make any PRs into develop as well.

**Comment by zhuyuping** [comment]
thanks you

**Comment by macdrevx** [comment]
Also, I just noticed that your original post says you’re using version 4. We don’t plan to release any more v4 updates, so this new feature would be added to v5.

**Comment by macdrevx** [comment]
Added in version 5.2.0
