### ISSUE TITLE
About MultiLineString Coordinates

### ISSUE THREAD

**Issue by zhuyuping** [GEOSwift/GEOSwift#175]
`let geo = offsetLine?.intersection(polygon)
let mutiLineString = geo as? MultiLineString
`

I want to be able to get [LineSting] or [[Coordinate]] of  mutiLineString
But now I seem to only get WKT or WKB

The way I am thinking of now is to parse WKT strings to generate objects similar to [LineSting] or [[Coordinate]]

Do I have a simpler and more efficient way to achieve my needs?

**Comment by macdrevx** [comment]
Are you using version 4 or 5?

**Comment by macdrevx** [comment]
This seems like a similar problem to #170.

**Comment by macdrevx** [comment]
So once you have a MultiLineString, you can access its geometries property which is a list of LineStrings. Then for each line string you can extract its coordinates. `map` should be useful.

**Comment by zhuyuping** [comment]
version 4

YES, This seems like a similar problem to #127 

But I don't know what you mean.
I understand that you mean this.

`
open class MultiLineString<T: LineString> : GeometryCollection<T> {
   var linestrings:[]     // a property to stored LineString List
}
`

**Comment by macdrevx** [comment]
You could write:

`multiLineString.geometries.map { $0 }`

to get `[LineString]`

You could append `.map { $0.coordinates }`

to get `[[Coordinate]]`

**Comment by macdrevx** [comment]
I'd also love for you to try out version 5 sometime. I think you'd find many of these types of things a bit easier in that version.

**Comment by zhuyuping** [comment]
thanks again
Because of the changes in the APIs of version 5 and version 4, I will switch to version 5 later.
