### ISSUE TITLE
using intersection method throw exception

### ISSUE THREAD

**Issue by zhuyuping** [GEOSwift/GEOSwift#176]
version 4.1.0

```
let p = Polygon(WKT: "POLYGON ((190 400, 185 114, 470 60, 845 87, 810 250, 695 317, 689 307, 682 298, 650 220, 646 210, 580 210, 580 320, 730 400, 965 382, 850 430, 650 430, 558 355, 553 345, 502 205, 455 334, 457 346, 458 356, 570 470, 690 480, 522 515, 220 480, 90 480, 40 210, 80 100, 150 240, 190 400))")
let l = LineString(WKT: "LINESTRING (206.4669095619841 1341.90722694549, 168.5330904380159 -827.90722694549)")
l?.intersection(p!)
```
 
exception is throw from 

```
void
FastNodingValidator::checkValid()
{
	execute();
	if (! isValidVar)
	{
		//std::cerr << "Not valid: " << getErrorMessage() << " interior intersection: " << segInt->getInteriorIntersection() << std::endl;
		throw util::TopologyException(getErrorMessage(), segInt->getInteriorIntersection());
	}
}
```

terminal message:
1. p getErrorMessage():
found non-noded intersection between LINESTRING (191.399 480, 187.5 257) and LINESTRING (150 240, 190 400)
2. p segInt->getInteriorIntersection():
(const geos::geom::Coordinate) $1 = (x = 190, y = 400, z = NaN)

**Comment by macdrevx** [comment]
I can't reproduce this error using GEOSwift 4.1.0. Can you please attach a sample project that reproduces the issue?

**Comment by macdrevx** [comment]
Nevermind, I set an exception breakpoint and was able to see it happen. Looks like geos uses C++ exceptions internally. If you turn off the exception breakpoint, you'll see that `l?.intersection(p!)` actually completes successfully.

**Comment by zhuyuping** [comment]
C++ exception, does it affect my normal use? I am worried that this exception will crash the normal APP.

**Comment by macdrevx** [comment]
Nope, it won’t impact the app. GEOSwift uses the geos C API which catches all exceptions from the C++ layer.
