### ISSUE TITLE
GEOSwift with Google Maps iOS SDK (Draw a polygon)

### ISSUE THREAD

**Issue by aahsanali** [GEOSwift/GEOSwift#177]
I am using GEOSwift library and I need help in:

1 - How can I draw polygon geometry data on Google Maps? I want to draw following geometry (polygon) on google map as an overlay:

`let geometry = try! Geometry(wkt: "POLYGON((35 10, 45 45.5, 15 40, 10 20, 35 10))")`
2 - How can I get Coordinates (lat, long) from the Geometry (geometry) back in form of string or CLLocationCoordiantes

I also posted a question on SO, but I need urgent help, thanks
https://stackoverflow.com/questions/57738403/geoswift-with-google-maps-ios-sdk-draw-a-polygon

**Comment by macdrevx** [comment]
I'll assume you're using Google Maps SDK for iOS version 3.3.0 and GEOSwift version 5.1.0.

As an aside, creating a GEOSwiftGoogleMaps add-on library would be a great addition to the GEOSwift family.

Now to your question. You have a polygon (without holes) represented as WKT and you want to show it on a Google Map. Specifically, you probably want to end up with a [GMSPolygon](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_polygon)

If you know that your WKT will always be a polygon, you can actually write

```
let polygon = try! Polygon(wkt: "POLYGON((35 10, 45 45.5, 15 40, 10 20, 35 10))")
```

If you can't guarantee that, you can do what you wrote initially

```
let geometry = try! Geometry(wkt: "POLYGON((35 10, 45 45.5, 15 40, 10 20, 35 10))")
```

and then extract the polygon using `if case let`/`guard case let`/`switch case let`:

```
switch geometry {
case let .polygon(polygon):
    // Do something with polygon
default:
    // handle other types of Geometry or fail here
}
```

Check the [definition of Geometry](https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/Core%20Types/Geometry.swift) that shows the other cases you might care to handle.

Once you have `polygon: Polygon`, you can get the points that represent its exterior:

```
let points = polygon.exterior.points
```

`Polygon.exterior` gives you a `Polygon.LinearRing` and `Polygon.LinearRing.points` gives you an array of `Point`.

Now that you have `points`, you can map them into an array of `CLLocationCoordinate2D`

```
let coords = points.map { p in CLLocationCoordinate2D(latitude: p.y, longitude: p.x) }
```

Note that y goes with latitude and x goes with longitude.

The rest of the process is basically info about how to use the Google Maps SDK, so I'll answer that part on StackOverflow instead.

**Comment by aahsanali** [comment]
@macdrevx Thanks a lot for your help. I am able to solve this problem now. 🥇

**Comment by aahsanali** [comment]
@macdrevx can you guide me to the equivalent functions for:

```
    Geometry .fromGeoJSON(_ URL: Foundation.URL) throws -> [Geometry]?
    Geometry.fromGeoJSONDictionary(_ dictionary: [String: AnyObject]) -> [Geometry]? 

```
in GEOSwift 5. 

Thanks

**Comment by macdrevx** [comment]
Sure. The first step is to get a representation of the JSON as `Data`. If you're starting with a file `URL`, you can say `Data(contentsOf: URL)`. If you have `dictionary: [String: AnyObject]` you'd need to use `NSJSONSerialization` or similar to convert it to `Data`.

Once you have `data: Data`, you can decode using:

```
let decoder = JSONDecoder()
let geoJSON = try decoder.decode(GeoJSON.self, from: data)
```
