### ISSUE TITLE
Carthage Compilation issue

### ISSUE THREAD

**Issue by SirWellington** [GEOSwift/GEOSwift#189]
Hi, I am having issues comping this library in Carthage.
Below is the line in my `Cartfile`

```
github "GEOSwift/GEOSwift" ~> 5.1.0
github "GEOSwift/GEOSwiftMapKit" ~> 1.0.0
```

Here is the error I am seeing.

```
GEOSwift+MapKit.swift:87:18: error: use of undeclared type 'MKMultiPolygon'
```
/Users/wellington/Documents/Code/GoHope/gohope-ios/GoHope/Carthage/Checkouts/GEOSwiftMapKit/GEOSwiftMapKit/GEOSwift+MapKit.swift:80:18: error: use of undeclared type 'MKMultiPolyline'
public extension MKMultiPolyline {
                 ^~~~~~~~~~~~~~~
/Users/wellington/Documents/Code/GoHope/gohope-ios/GoHope/Carthage/Checkouts/GEOSwiftMapKit/GEOSwiftMapKit/GEOSwift+MapKit.swift:87:18: error: use of undeclared type 'MKMultiPolygon'
public extension MKMultiPolygon {
```

Please help.

**Comment by SirWellington** [comment]
Turns out the version of the library I was using only works for XCode 11+ 
I am still on XCode 10.3. Reverting tot the following versions worked for me:

```
github "GEOSwift/GEOSwift" "5.1.0"
github "GEOSwift/GEOSwiftMapKit" "1.0.0"
```

**Comment by macdrevx** [comment]
Thanks for reporting this, and sorry for the incompatibility. Looks like I need to test more thoroughly next time. I thought I’d limited that new code to newer Xcode versions.
