### ISSUE TITLE
Expression of type 'Geometry' is unused.

### ISSUE THREAD

**Issue by jtchristie** [GEOSwift/GEOSwift#193]
I implemented the code into my MapView, but it brings up the warning. I want to put point markers on each of the locations in my GEOJson file.

**Comment by macdrevx** [comment]
Hi @jtchristie, can you share some more info? Version of GEOSwift, example code that reproduces the issue.

**Comment by jtchristie** [comment]
![image](https://user-images.githubusercontent.com/48321241/73586088-7e4f6080-445d-11ea-875c-82178ca0e494.png)

This is the code from my mapView. The GEOJson file has multiple locations, each of which I want to make a point.  I am using the most current version of GEOSwift using Cocoapods. I also added the Swift Package Manager because I thought that may have been the issue.

**Comment by macdrevx** [comment]
Hi @jtchristie, it looks like you made it pretty far through decoding the GeoJSON. The warning that you're seeing just means that that line of code doesn't do anything. It evaluates the expression `coffeeMap` which is a `Geometry` but then that's all the line says, so it just goes on to the next line without doing anything else.

Regarding CocoaPods & Swift Package Manager, you shouldn't need both of them to use GEOSwift. One or the other will do.

You may also be interested in https://github.com/GEOSwift/GEOSwiftMapKit which contains additional convenience methods to [help create MapKit annotations and overlays](https://github.com/GEOSwift/GEOSwiftMapKit/blob/master/GEOSwiftMapKit/GEOSwift%2BMapKit.swift) from GEOSwift values.

I think your next step should be to take `coffeeMap` and convert it into MapKit annotations or overlays that you can add to your `MKMapView`. Probably the first thing you'll need to do is figure out which type of Geometry coffeeMap is. Geometry is an enum that can represent any of the basic geometry values. You can see the different possibilities in its [declaration](https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/Core%20Types/Geometry.swift). You'll want to use `case let` to extract the associated value for whichever case you're dealing with. I see you've already used that technique to extract the feature from the GeoJSON. So, for example if your GeoJSON has a collection of points, you might update your code to say:

```
if …your existing code goes here except for the last line of the if statement, which changes to…
case let .some(.geometryCollection(collectionOfPoints)) = feature.geometry {

    // now you can use collectionOfPoints
    // maybe you want to iterate over the geometries in the collection and convert them to Points
    // this will do that and ignore any geometries of other types
    let points = collectionOfPoints.geometries.compactMap { (geometry) -> Point? in
        if case let .point(p) = geometry {
            return p
        }
        return nil
    }

    // then, using GEOSwiftMapKit you could convert point into annotations:

    let pointAnnotations = points.map { (point) in MKPointAnnotation(point: point) }

    // at this point, it's up to you to take pointAnnotations and add them to your map.
}
```

If your data has different types of values, you'll have to modify this accordingly, but the general principles should be the same.

Hope this helps!

**Comment by jtchristie** [comment]
Hi again, upon working with the code you gave me I noticed that the code within the if statement was not running. I used generic data from the GeoJSON Wikipedia page as test code to make sure that it wasn't formatting issues. So for some reason the if statement is not evaluating true and is printing the error. Please get back to me about this

![image](https://user-images.githubusercontent.com/48321241/73677684-a14f5f80-466b-11ea-96c4-6273d98b9dee.png)

**Comment by macdrevx** [comment]
Can you share the example data that reproduces the problem?

**Comment by jtchristie** [comment]
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [102.0, 0.5]
      },
      "properties": {
        "prop0": "value0"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
        ]
      },
      "properties": {
        "prop0": "value0",
        "prop1": 0.0
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
            [100.0, 1.0], [100.0, 0.0]
          ]
        ]
      },
      "properties": {
        "prop0": "value0",
        "prop1": { "this": "that" }
      }
    }
  ]
}

https://en.wikipedia.org/wiki/GeoJSON
This is from GeoJSON's Wikipedia page.

**Comment by macdrevx** [comment]
So in that example, the top-level type is FeatureCollection, but your code is expecting a feature. Try this…

```
if let geoJSONURL = Bundle.main.url(forResource: "Test", withExtension: "geojson"),
    let data = try? Data(contentsOf: geoJSONURL),
    let geoJSON = try? decoder.decode(GeoJSON.self, from: data),
    case let .featureCollection(featureCollection) = geoJSON,
    …
```

At that point, you'd need to update the rest of your code to handle multiple features (or just take the first feature in the feature collection).

(Also, in the future, when sharing code, please just copy paste instead of using screenshots. It makes it easier for others to try out your code or suggest edits.)

**Comment by macdrevx** [comment]
I wanted to add that if you are directly controlling the data and you *know* what type it is, you can decode directly to that type rather than decoding to `GeoJSON` as an intermediate. You only need `GeoJSON` when you need to be able to handle any valid GeoJSON input.
