### ISSUE TITLE
Cannot Install GEOSwift using spm or Carthage

### ISSUE THREAD

**Issue by denisatoderean** [GEOSwift/GEOSwift#195]
**Environment**

Xcode: 11.3.1
Swift Version: 5.1.3
MacOS: macOS Catalina 10.15.3

**crash**
dyld: Library not loaded: @rpath/geos.framework/geos
  Referenced from: "/Users/...."
  Reason: image not found

**Please update your instructions.**

I also tried installing it using **Carthage** but it doesn't generate any .framework

**Comment by macdrevx** [comment]
Hi @denisatoderean, can you share the steps you followed and a `Package.swift` or `Cartfile` or other example project that we can use to recreate the issue?

**Comment by denisatoderean** [comment]
Just add  `github "GEOSwift/GEOSwift" ~> 6.0.0` in the Cartfile and run `carthage update`
or add `https://github.com/GEOSwift/GEOSwift.git` in SPM. I don't need to create a no Package.swift file in my project.

**Comment by bryan1anderson** [comment]
Same issue. All I did was plug in `.package(url: "https://github.com/GEOSwift/GEOSwift.git", from: "6.0.0")` to my package and then added "GEOSwift" as a dependency

**Comment by macdrevx** [comment]
I just tried Carthage (v0.34.0) and SPM (5.1.3) and both are working for me.

Could either of you attach a zip of a sample project that I could use to try to reproduce the issue?

**Comment by macdrevx** [comment]
Hi @denisatoderean and @bryan1anderson since I haven't heard from you and can't reproduce this issue, I'm going to close it for now. Please reopen it if you can attach a sample project that demonstrates the issue.

**Comment by denisatoderean** [comment]
[GEOSwiftError.zip](https://github.com/GEOSwift/GEOSwift/files/4371419/GEOSwiftError.zip)
Just run this project, I did nothing but plug it in using SPM

**Comment by macdrevx** [comment]
Thank you, I can reproduce the problem using this sample project. I've been testing using swift on the command line, and it seems like this is set up differently than the way I've been testing. I'll see if I can figure out what's going on. In the meantime, maybe you could provide a more detailed description of exactly the steps you followed. A screen recording could be a good way to show it.

**Comment by macdrevx** [comment]
@denisatoderean I think I see what the problem is, although I'm surprised that Xcode doesn't handle this more gracefully. GEOSwift depends on geos. geos is [configured](https://github.com/GEOSwift/geos/blob/master/Package.swift) to be a dynamic library, which means that for iOS apps it needs to be embedded in the app bundle. The example project you shared doesn't do that, but if you explicitly add geos to your dependencies, it works just fine:

<img width="1473" alt="Screen Shot 2020-03-23 at 7 48 46 PM" src="https://user-images.githubusercontent.com/205658/77373727-57b3f480-6d3f-11ea-8a7a-0197d0c99a02.png">

**Comment by denisatoderean** [comment]
@macdrevx Meanwhile I have figured this out, but I was hoping you could update your documentation :)

**Comment by macdrevx** [comment]
Will do

**Comment by macdrevx** [comment]
Updated the readme with a note about this.

**Comment by macdrevx** [comment]
It also appears as though this issue may be fixed with Xcode 11.4

**Comment by borut-t** [comment]
I have an issue with the latest Xcode 11.4.1. I've included geos package also. I get this:
```
Undefined symbol: ___llvm_profile_runtime
```

**Comment by macdrevx** [comment]
Hi @borut-t. I think this sounds like a different problem. Can you open a new issue? I tried to reproduce it but I could not do so. Can you also attach a sample project that demonstrates the problem?

**Comment by borut-t** [comment]
Hey @macdrevx. I've tried with a clean project and it works as expected 😞

However, here is the complete error message I am facing on my project if it helps:
<img width="1324" alt="Screenshot 2020-05-05 at 12 07 24" src="https://user-images.githubusercontent.com/677166/81056036-24ca5800-8eca-11ea-9f3f-3a2a7cc1ead9.png">

**Comment by macdrevx** [comment]
Check out this thread. Sounds like this might be an issue with Xcode: https://github.com/Swinject/Swinject/issues/296

**Comment by borut-t** [comment]
I can't believe turning off code coverage solved it. Thanks @macdrevx 🙌
