### ISSUE TITLE
App delivery issue with SPM

### ISSUE THREAD

**Issue by borut-t** [GEOSwift/GEOSwift#204]
When I push a build with GEOSwift installed via SPM, I get the following error:
`TMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.`

I have two targets. Could that be the issue?

**Comment by macdrevx** [comment]
@borut-t which platform are you building for? Which version of GEOSwift?

**Comment by borut-t** [comment]
@macdrevx the latest version of GEOSwift on iOS.

**Comment by macdrevx** [comment]
Thinking through a few things to check…

1. What version of Xcode/Swift?
2. It's probably not this, but just in case, did you list both GEOSwift and geos in your Package.swift?
3. If you export an archive build and then inspect the package contents, can you determine whether any dynamic libraries are missing from the bundle?
4. Have you made any customizations to the dylib search path in your target's/project's build settings?

**Comment by borut-t** [comment]
> Thinking through a few things to check…
> 
> 1. What version of Xcode/Swift?

Xcode 11.6, Swift 5.2.x

> 2. It's probably not this, but just in case, did you list both GEOSwift and geos in your Package.swift?

No, just GEOSwift and GEOSwiftMapKit

> 3. If you export an archive build and then inspect the package contents, can you determine whether any dynamic libraries are missing from the bundle?

Using `otool -L` command I can only see the following line related to geosswift:
`@rpath/geos.framework/geos (compatibility version 0.0.0, current version 0.0.0)`

I would say it should not be there since other SPM packages are also omitted here 🤔 

> 4. Have you made any customizations to the dylib search path in your target's/project's build settings?

I did not

**Comment by macdrevx** [comment]
@borut-t sorry for the delayed reply. I recommend that you try listing [geos](https://github.com/GEOSwift/geos) in your Package.swift. Even though it's a dependency of GEOSwift, [other folks have encountered issues](https://github.com/GEOSwift/GEOSwift/issues/195) that were resolved by including it.

Even though your other SPM packages are omitted in the output from `otool -L` I believe it is correct for geos to be listed there because it's [configured to produce a dynamic library](https://github.com/GEOSwift/geos/blob/master/Package.swift#L9) whereas by default SPM packages are linked statically.

**Comment by borut-t** [comment]
@macdrevx I've tried explicitly adding geos as a package and I get the following error:
`Undefined symbol: ___llvm_profile_runtime`

<img width="628" alt="Screenshot 2020-08-05 at 08 38 20" src="https://user-images.githubusercontent.com/677166/89379956-08bb9a00-d6f7-11ea-8f26-94dd9c181cba.png">

**Comment by macdrevx** [comment]
Is it the same problem as we ran into before? https://github.com/GEOSwift/GEOSwift/issues/195#issuecomment-624016457

That time, sounds like you just had to disable code coverage.

**Comment by borut-t** [comment]
@macdrevx I've totally forgotten we had the same issue before. It works now. Thanks 🙌

**Comment by Ceylo** [comment]
So we have to choose between GEOSwift and code coverage? That's really a no-go for me…
