### ISSUE TITLE
How to convert to a mapshape?

### ISSUE THREAD

**Issue by joeuelk** [GEOSwift/GEOSwift#208]
I'm having trouble updating my code to work with API version 5.

I'm stuck on how to convert a decoded geojson to a MultiPolygon or Polygon to display as a map overlay.

```
case let .feature(myFeature):
     let geometryMapShape = try GeometryMapShape(geometry: myFeature.geometry!)
     let geometryConvertible = geometryMapShape.geometry
     if let geo = geometryConvertible as? MultiPolygon {
          // code here
     }
```

I can load the geojson file, get it detected as a "feature" but haven't had much luck beyond that. I haven't found any sample code with the new API that covers this.

Thanks

**Comment by joeuelk** [comment]
Closing for now

**Comment by macdrevx** [comment]
@joeuelk if you want to share an example geojson, I’d be happy to help
