### ISSUE TITLE
Geos build issue

### ISSUE THREAD

**Issue by Adraesh** [GEOSwift/GEOSwift#209]
Hello,

I have an issue while building on Xcode 12.1:

```
Include of non-modular header inside framework module 'geos.geos_c': '~/projects/my_project/my_project/libspatialite/include/geos/export.h'
```

I tried different things:

- Setting the Target membership of geos folder to Public
- Setting to YES "Allow Non-modular Includes in Framework Modules"

but still it's not working.

Thanks in advance.

EDIT: I forgot to mention that the issue happens only when using the Swift UI preview mode. I can build and play the app on simulator though.

**Comment by macdrevx** [comment]
Thanks for reporting this. Can you share a sample project we can use to reproduce the issue?

**Comment by Adraesh** [comment]
Hello,

In fact I might post a bit fast on this github.

The issue is not related to GeoSwift pod/lib but to my Spatialite lib I compiled.

For those who can ran into the same issue, I simply replaced the include bellow:

```
#include <geos/export.h>
```
by
```
#include "export.h"
```

And the preview mode works again.

Sorry for the disturbance here.

**Comment by macdrevx** [comment]
No problem. Thanks for letting us know, and do let us know if you run into any other GEOSwift issues.
