### ISSUE TITLE
How to calculate the distance between two surfaces

### ISSUE THREAD

**Issue by fenghedemo1** [GEOSwift/GEOSwift#210]
Hello, I am a novice in this field, my SWIFT level is not high, I can not understand your code, I would like to calculate a point to the surface of the distance, or face to face distance, how to do

**Comment by macdrevx** [comment]
It sounds like you are working with 3D geometry. Is that true? GEOSwift only supports 2D geometry.

**Comment by fenghedemo1** [comment]
Is there any documentation for this library? I can't find the functionality I want in your code.
I think the function I want should be 2D

**Comment by fenghedemo1** [comment]
I'm using mapBox, and I want to realize the distance from one point to one face, or from one face to another.

**Comment by fenghedemo1** [comment]
Or is there a demo or something

**Comment by fenghedemo1** [comment]
My android colleague found the LIBRARY JTS, which can calculate the distance between the middle point and the surface of two-dimensional geometry. I found that the library is JAVA, which does not support iOS. Later, I discovered GEOS and finally found your library. I want to know how the methods provided in your library work. What do they stand for respectively

**Comment by fenghedemo1** [comment]
Can you provide a small demo of a function

**Comment by fenghedemo1** [comment]
Hello, I'm going to call your short method, I saw this method is public func short (to geometry: GEOSwift. GeometryConvertible) throws - > Double

I need to encapsulate a method to compute them and here's my method, can Polygon and Polygon1 only be initialized by the bottom like this? Can I pass coordinates into polygon and Polygon1 initialization by my for loop for Coords in Coordinates above? Here's how I did it

public func calculatPointToPolygon(coordinates:Array<CLLocation>) -> Double    {

var Pointarray   = ()
for coords in coordinates {
//            let point1  = Point(x: coords.coordinate.latitude, y: coords.coordinate.longitude)


//            Pointarray.append(point1)
}
let polygon = try! Geometry(WKT: "POLYGON(35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30) ")
let polygon1 = try! Geometry(WKT: "POLYGON(35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30) ")
//            try! polygon.intersects(polygon1)
return try! polygon.distance(to: polygon1)



}

**Comment by fenghedemo1** [comment]
Hello, I'm going to call your distance method, I saw this method is public func distance (to geometry: GEOSwift. GeometryConvertible) throws - > Double

I need to encapsulate a method to compute them and here's my method, can Polygon and Polygon1 only be initialized by the bottom like this? Can I pass coordinates into polygon and Polygon1 initialization by my for loop for Coords in Coordinates above? Here's how I did it

public func calculatPointToPolygon(coordinates:Array<CLLocation>) -> Double    {

var Pointarray   = ()
for coords in coordinates {
//            let point1  = Point(x: coords.coordinate.latitude, y: coords.coordinate.longitude)


//            Pointarray.append(point1)
}
let polygon = try! Geometry(WKT: "POLYGON(35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30) ")
let polygon1 = try! Geometry(WKT: "POLYGON(35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30) ")
//            try! polygon.intersects(polygon1)
return try! polygon.distance(to: polygon1)



}

**Comment by fenghedemo1** [comment]
I want to know how to pass the latitude and longitude from the for loop to Polygon and Polygon1 to call your method distance

**Comment by macdrevx** [comment]
Does this help?

```
// Use case 1: distance between 2 polygons
let polygon = try! Geometry(wkt: "POLYGON((35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30))")
let polygon1 = try! Geometry(wkt: "POLYGON((35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30))")
let distance1 = try! polygon.distance(to: polygon1)

// Use case 2: distance between a point and a polygon
let point = Point(x: 0, y: 0)
let distance2 = try! polygon.distance(to: point)
```

I'm not sure I understand what you're trying to do, so please let me know if this isn't what you need.

**Comment by fenghedemo1** [comment]
Yes, thank you. I find that most of the operations provided in the library are between two geometries. Can the library determine if there are intersections in a plane? In other words, it's a face, is there any overlap.
<img width="810" alt="WeChatd48a17d1b7ec8122a8c2ed577e61fe71" src="https://user-images.githubusercontent.com/15060009/97402190-14e97900-192d-11eb-9729-8383638fe1cf.png">
The top one I think is a legitimate polygon
The bottom one I think is an illegal polygon
How can I tell if they are legal

**Comment by fenghedemo1** [comment]
<img src="https://user-images.githubusercontent.com/15060009/97402281-43ffea80-192d-11eb-8a92-94d2a4b0d977.png">

**Comment by fenghedemo1** [comment]
Yes, thank you. I found that most of the operations provided in the library fall between two geometries. Can the library determine if there are intersections on the plane? In other words, this is a face, is there any overlap. I think the top one is a legitimate polygon and I think the bottom one is an illegitimate polygon how do you know if they're legitimate

**Comment by fenghedemo1** [comment]
Yes, thank you. I found that most of the operations provided in the library fall between two geometries. Can the library determine if there are intersections on polygons? In other words, to determine if a polygon has any overlap.

**Comment by fenghedemo1** [comment]
Similar to the picture of my head, I think the red polygon on the top is normal and the red polygon on the bottom is illegal because it overlaps. How to achieve such a judgment

**Comment by macdrevx** [comment]
There's a GEOS function `GEOSisValid_r` that checks for that condition, but we haven't added it to GEOSwift yet. We can easily add it though. It will follow the [implementation pattern](https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/GEOS/GeometryConvertible%2BGEOS.swift#L74-L76) of `isEmpty`.

I can probably add it within the next week, but let me know if you'd like to try to do it yourself.

**Comment by macdrevx** [comment]
GEOS (and therefore GEOSwift) follows the behavior of JTS. Here's what [the JTS docs say](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Polygon.html) constitute a valid polygon:

> A Polygon is topologically valid if and only if:
> 
> - the coordinates which define it are valid coordinates
> - the linear rings for the shell and holes are valid (i.e. are closed and do not self-intersect)
> - holes touch the shell or another hole at at most one point (which implies that the rings of the shell and holes must not cross)
> - the interior of the polygon is connected, or equivalently no sequence of touching holes makes the interior of the polygon disconnected (i.e. effectively split the polygon into two pieces).

[The docs for is valid](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#isValid--) indicate that these are the rules that it follows to determine validity.

We may need to explore using `GEOSisValidReason_r` and `GEOSisValidDetail_r` if we want to be able to determine the exact reason why the polygon was invalid (e.g. was it invalid due to a self-intersection, or for some other reason?).

**Comment by fenghedemo1** [comment]
let polygon =   try! Geometry(wkt: polyonStr)
        let polyon1 = try!  polygon.makeValid()

        return try! polygon.isTopologicallyEquivalent(to: polyon1)

In this way, it seems that I can also determine whether a polygon is valid or not. But it's not clear how rigorous this approach is. If not, please let me know when you add it next week.

**Comment by macdrevx** [comment]
@fenghedemo1 please try out the new `isValid`, `isValidReason`, and `isValidDetail` functions added in #211 

You can do this by specifying the branch name `validity` for GEOSwift in your package manager. Let me know how it goes. I'm going to wait a day or two to make sure there's no other feedback before I merge into master.

**Comment by fenghedemo1** [comment]
Okay, we're done
