### ISSUE TITLE
多边形周长面积问题

### ISSUE THREAD

**Issue by fenghedemo1** [GEOSwift/GEOSwift#213]
您好,我看到您库中有length和area,我想他们分别代表周长和面积,但是当我传进入一个多边形经纬度顶点进去以后,他们两个算出来的结果都是很小的数字,类似0.02323....我想知道这两个分别如何使用,他们返回的单位又是什么  这是我构建多边形的方式
let polygon = try! Geometry(wkt: "POLYGON((39.984118 116.297110,39.984145 116.297936,39.983892 116.297947,39.983876 116.297110,39.984118 116.297110))")    
return try! polygon.area()
得出的结论都是很小的小数

**Comment by macdrevx** [comment]
Hi @fenghedemo1, I'm going off of the following Google Translate output, so please let me know if I'm answering the wrong question:

> Hello, I see that there are length and area in your library. I think they represent the perimeter and area respectively, but when I pass in the latitude and longitude vertices of a polygon, the results of the two calculations are very small numbers. Similar to 0.02323.... I want to know how these two are used, and what is the unit they return. This is how I construct the polygon
let polygon = try! Geometry(wkt: "POLYGON((39.984118 116.297110,39.984145 116.297936,39.983892 116.297947,39.983876 116.297110,39.984118 116.297110))")
return try! polygon.area()
The conclusions reached are all very small decimals

GEOSwift geometry is always done on the Cartesian plane. So the output that you get is just arbitrary squared units. For example, if you took a 2x2 square `POLYGON((0 0,0 2,2 2,2 0,0 0))` you should get an area of 4.

You'll need a different library (or your own implementation) to convert this to something like square meters.
