### ISSUE TITLE
debug模式报错

### ISSUE THREAD

**Issue by fenghedemo1** [GEOSwift/GEOSwift#214]
按照文档,使用cocopods集成后,在debug模式下报错
Showing All Messages
Undefined symbol: protocol witness for GEOSwift.WKTInitializable.init(wkt: Swift.String) throws -> A in conformance GEOSwift.Geometry : GEOSwift.WKTInitializable in GEOSwift

在realease模式下不会报错,请问如何解决

**Comment by macdrevx** [comment]
Hi thank you for this report. Could you please provide some more information? What version of GEOSwift are you using? How did you specify it in your Podfile? If possible, could you attach an example Xcode project and instructions for how to reproduce the problem?

**Comment by macdrevx** [comment]
Closing as stale. Feel free to reopen with additional information if you're still encountering this issue.
