### ISSUE TITLE
LineString buffer not working as expected

### ISSUE THREAD

**Issue by tsuz** [GEOSwift/GEOSwift#216]
Previous: https://github.com/GEOSwift/GEOSwift/issues/215

**What**

[Initial, generated and output data](https://github.com/GEOSwift/GEOSwift/files/6019095/Archive.zip)

| print | image  |
|--|--|
| print("initial data", json) |  ![Screen Shot 2021-02-22 at 10 47 41](https://user-images.githubusercontent.com/6927131/108647500-28cc7280-74fc-11eb-9aa7-646b2714c5d3.png) | 

| expected (red line) | observed | 
|--|--|
| ![Screen Shot 2021-02-22 at 10 47 41 copy](https://user-images.githubusercontent.com/6927131/108647719-b90ab780-74fc-11eb-97e4-9c224bfeece6.png) | ![Screen Shot 2021-02-22 at 10 49 38](https://user-images.githubusercontent.com/6927131/108647594-68935a00-74fc-11eb-8701-b03cf04d57b7.png) |

```
         if let json = String(data: collection, encoding: .utf8) {
           print("initial data", json)
        } 

        for feature in featureCollection.features {
            if case let .lineString(lineString) = feature.geometry {
                linestrings.append(lineString)
                if let data = try? JSONEncoder().encode(lineString) {
                    let json = String(data: data, encoding: .utf8)
                    print("item json", json)
                }
                guard let buf = try? lineString.buffer(by: 1).geometry else {
                    return
                }
                if let data2 = try? JSONEncoder().encode(buf) {
                    let json = String(data: data2, encoding: .utf8)
                    print("item json 2", json)
                }
            }
        }
```

Can anyone see what I'm doing wrong here?

**Comment by macdrevx** [comment]
In GEOSwift, everything is just math, so since your input geometry is in lat/long coordinates, buffer(1) means that you're trying to buffer by 1 degree of latitude and 1 degree of longitude, which, based on the description is not what you want. Try using a much smaller value.

**Comment by macdrevx** [comment]
That said, I'll admit that I'm confused by the output shape. I'll take a closer look at that.

**Comment by tsuz** [comment]
@macdrevx 

Thanks for the fast reply!

I assumed the `buffer(width: Double)` was in meters. After updating this to a smaller value, it worked as expected!

```
guard let buf = try? lineString.buffer(by: width).geometry else {
  return
}
```

| width=0.0001 | width=0.0005 |
|--|--|
| ![Screen Shot 2021-02-22 at 11 15 38](https://user-images.githubusercontent.com/6927131/108648827-772f4080-74ff-11eb-8cf5-c3f85df5ecef.png) | ![Screen Shot 2021-02-22 at 11 18 28](https://user-images.githubusercontent.com/6927131/108648952-bcec0900-74ff-11eb-9295-2c7975c22cb8.png) |


Thanks again!

**Comment by macdrevx** [comment]
I did a little more investigation into this issue and discovered that GEOSwift is passing 0 for the `quadsegs` parameter of geos's buffer function which is leading to some of those flat edges around the outside of the buffered corners. In another location internally, GEOS uses a value of 8 as a default, which results in a result that is closer to what you might expect on first glance. I'll push an update with this change.

**Comment by macdrevx** [comment]
Here's the before and after:

| quadsegs=0 | quadsegs=8 |
|--|--|
| ![quadsegs=0](https://user-images.githubusercontent.com/205658/109430727-6cc1ea80-79c8-11eb-969f-64b575a09132.png) | ![quadsegs=8](https://user-images.githubusercontent.com/205658/109430730-6e8bae00-79c8-11eb-92ea-de7c0a74374c.png) |

**Comment by macdrevx** [comment]
Updated in https://github.com/GEOSwift/GEOSwift/releases/tag/8.0.2
