### ISSUE TITLE
Provisioning profile error, when archiving, xcode @ version 6.0.2

### ISSUE THREAD

**Issue by DanielWinduss** [GEOSwift/GEOSwift#219]
error: geos does not support provisioning profiles. geos does not support provisioning profiles, but provisioning profile <my provisioning profile> has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'geos' from project 'geos')

**Comment by macdrevx** [comment]
Hi @DanielWinduss, could you please provide a minimal test project that reproduces this issue or instructions on how to create one?

**Comment by macdrevx** [comment]
Closing as stale. Please feel free to reopen with new information if you're still experiencing this issue.
