### ISSUE TITLE
Release 7.0 removes negative buffer with no alternative

### ISSUE THREAD

**Issue by ProjectDent** [GEOSwift/GEOSwift#221]
I was using the buffer function with a negative value to reduce the size of a geometry. I was previously using v5.1.0. After a change in v7.0.0 to remove support for negative buffer, there is no way to achieve the same result.

**Comment by macdrevx** [comment]
Thanks for sharing your use case. I'll take a look.

**Comment by macdrevx** [comment]
Hi @ProjectDent, could you please take a look at the proposed change to address this issue? https://github.com/GEOSwift/GEOSwift/pull/224

**Comment by ProjectDent** [comment]
This looks great, but I will test properly soon and let you know. Thank you for taking the time.

**Comment by macdrevx** [comment]
I'm going forward with the fix. Please reopen if you discover any issues.
