### ISSUE TITLE
The distance between two polygons

### ISSUE THREAD

**Issue by fenghedemo1** [GEOSwift/GEOSwift#222]
Can you calculate the distance between the two polygons, similar to the distance between the two irregular polygons in the picture in my personal information profile picture

**Comment by fenghedemo1** [comment]
2D

**Comment by macdrevx** [comment]
All geometries have the `distance(to:)` method. Does that work for your use case? Which distance are you looking for? The minimum distance? The distance between the centroids? Something else?

**Comment by macdrevx** [comment]
Hi @fenghedemo1, did this resolve your question?

**Comment by macdrevx** [comment]
Closing, but feel free to reopen if this didn't resolve your question.
