### ISSUE TITLE
logic that handle two polygons union

### ISSUE THREAD

**Issue by killerm250m** [GEOSwift/GEOSwift#223]
I wonder where I can find the logic that handles two polygons unions I tried to search in the files but without luck!

**Comment by macdrevx** [comment]
Check out [`union(with:)`](https://github.com/GEOSwift/GEOSwift/blob/main/GEOSwift/GEOS/GeometryConvertible%2BGEOS.swift#L309-L311)

That file contains a bunch of methods that can be used on any type of geometry

**Comment by killerm250m** [comment]
i am trying to port the logic that handles polygon union but I can't found any in that file.

**Comment by macdrevx** [comment]
I see. For that, you'll need to locate at the underlying implementation which is in GEOS: https://github.com/libgeos/geos.
