### ISSUE TITLE
Default geometry? (more Swift question than GeoSwift)

### ISSUE THREAD

**Issue by NasH5169** [GEOSwift/GEOSwift#229]
Hello,

I am wondering if it is possible to write in Swift a function that always return a valid geometry:

`
func getValidGeometry(wkt: String) -> Geometry {
  do {
    return try Geometry(wkt: coordinates)    
  } catch {
    return try! Geometry(wkt: "POINT(0 0)")
  }
}
`

This function will work but Swift will consider that this function can throw. Swift is right but it will be great that GEOSwift can provide a basic geometry without potential throw.

What do you think about that?

Thanks!

**Comment by macdrevx** [comment]
You can create a point without the risk of throwing by avoiding the wkt init method: `let point = Point(x: 0, y: 0)`. Convert it to `Geometry` by either `point.geometry` or `Geometry.point(point)`

**Comment by NasH5169** [comment]
Thank you, I did not know it was possible. 👍
