### ISSUE TITLE
Support for subtracting geometries from others?

### ISSUE THREAD

**Issue by ProjectDent** [GEOSwift/GEOSwift#230]
There are usually 4 ways of combining different polygons, which have different names depending on who you ask. Here are some examples:

![image](https://user-images.githubusercontent.com/1865635/145707654-4c1f9b40-4f65-4574-8f04-2cc2e26b6f34.png)

![image](https://user-images.githubusercontent.com/1865635/145707660-c13cdb24-9c3c-4741-a41f-242ef58c772c.png)

![image](https://user-images.githubusercontent.com/1865635/145707673-82348ab0-70f5-4306-a2f4-f3cfb3b71eb1.png)

In GEOSwift, we have **Union**, **Intersection** and **Difference**. But as far as I know, we don't have **Subtract**.

Is there a particular reason that Subtract is missing, or if not, can it be added?

**Comment by macdrevx** [comment]
geos offers difference and symmetric difference, but only difference is exposed by GEOSwift at the moment. We can add symmetric difference.

Would that address what you're looking for?

**Comment by ProjectDent** [comment]
I’ve found various images online which actually show Didference as being what I was describing, where I thought difference did what is here labelled as Symmetric Difference. So may be that I don’t need it for now, but depending on how much work it’d be and other factors, it’d be best to be feature-complete.


![](https://www.learnbyexample.org/wp-content/uploads/python/Python-Set-Operatioons.png)
