### ISSUE TITLE
Inaccurate heatmap output. Maybe My Code is Wrong?

### ISSUE THREAD

**Issue by chitgoks** [GEOSwift/GEOSwift#244]
Hi all. i am using this lib to generate heatmap using google maps utils GMUHeatmapTileLayer but the output is not the same from my android app (which is the correct rendering)

Wish to ask if the GeoSWIFT classes i used is correct. this is my code
```
let featureCollection = try JSONDecoder().decode(FeatureCollection.self, from: Data(jsonString.utf8)) as FeatureCollection
            var weightedCoordinates: [GMUWeightedLatLng] = []
            for feature in featureCollection.features {
                if case let .point(point) = feature.geometry {
                    weightedCoordinates.append(GMUWeightedLatLng(
                        coordinate: CLLocationCoordinate2D(latitude: point.y, longitude: point.x),
                        intensity: 1
                    ))
                }
            }
            heatmap = GMUHeatmapTileLayer()
            heatmap?.weightedData = weightedCoordinates
```

And i am using this data source 

https://earthquake.usgs.gov/fdsnws/event/1/query?starttime=2022-09-23&format=geojson&minlatitude=4&maxlatitude=21&minlongitude=112&maxlongitude=132

android rendering
<img width="345" alt="Screen Shot 2022-10-23 at 11 29 21 PM" src="https://user-images.githubusercontent.com/3955470/197401052-9b3654ac-57cf-4626-947e-4c3f3afe6632.png">

ios rendering
<img width="350" alt="Screen Shot 2022-10-23 at 11 31 57 PM" src="https://user-images.githubusercontent.com/3955470/197401205-76549a42-90a0-46b2-8c46-f37883198b08.png">

Thoughts? Am i lacking some GeoSWIFT code to make this work? Or could be the intensity property of GMUWeightedLatLng that is the issue (im not familiar with this why they have a different way to generate heatmap since in android, i just threw all the coordinates and it handled everything).

**Comment by macdrevx** [comment]
GEOSwift code looks correct to me. Could you write some test code without using GEOSwift to verify the behavior of GMUHeatmapTileLayer and GMUWeightedLatLng on iOS match how they work on Android?

**Comment by chitgoks** [comment]
I will get back to you. I will also try to ask in their google maps utils if the rendering is different or the same in android and ios. and sorry, i re-read my post and i didnt point out that I used a different lib for android (simple features) but i didnt use it for ios because they do not have a pure swift library for it, only objective c so i decided to use this one.

**Comment by chitgoks** [comment]
I decided to try the simple features and see if the result is the same. so it looks like the rendering in google maps is different in ios and android.
