### ISSUE TITLE
Question: Storing large GeoJSON Files for usage with GEOSwift

### ISSUE THREAD

**Issue by ipadmini22** [GEOSwift/GEOSwift#245]
Hi,

I love the library created by you and would want to integrate it into my current project. One issue I got - and do not really know whom to ask - is storing large GeoJSON datasets locally on the device while keeping them available for your library to use.

Specifically: I got around 750 MB of GeoJSON data at the moment. This data needs to be stored fully locally, I cannot rely on a server to send the data all the time. On this dataset I need to perform regular calculations: namely intersects with lines (to find out which features intersect with a given line) and with points (to find out whether that point lies inside of any polygon).

Do you have any idea how to achieve this? On server-side there are great solutions, but I am a bit lost natively.

I hope you can help me!

**Comment by macdrevx** [comment]
Hi @ipadmini22 this isn't a use case that we support directly at the moment, but please share if you find a solution, especially one involving GEOSwift.

**Comment by ipadmini22** [comment]
@macdrevx ok, thanks for your prompt reply :). I will have to look into it, but probably switch to performing those queries server-side. Makes life just easier.
