### ISSUE TITLE
Request: concave hull support

### ISSUE THREAD

**Issue by alessdiimperio** [GEOSwift/GEOSwift#256]
Great framework. Any chance of support for concave hull algorithm that builds on top of the convex hull ?

**Comment by macdrevx** [comment]
Might https://github.com/GEOSwift/GEOSwift/blob/main/Sources/GEOSwift/GEOS/Boundable.swift be what you're looking for?

**Comment by alessdiimperio** [comment]
Aha ill chwck it out, perhaps misunderstoor the  image as it shower just lines and not filled in. If it works itll make my day

**Comment by alessdiimperio** [comment]
Hmm im not sure i understand the usage of boundary.

What im trying to resolve is when users intersect lines in a polygon. instead of throwing an error, i want to ignore the internal intersection and create a polygon without the internal holes.

the concave hull algorithm is supposed to do just that. How can boundary be used for the same outcome?

<img width="295" alt="Screenshot 2023-03-08 at 14 12 58" src="https://user-images.githubusercontent.com/82949084/223722592-7e9ce569-da52-4524-889e-ce58d3b773c1.png">
<img width="290" alt="Screenshot 2023-03-08 at 14 14 39" src="https://user-images.githubusercontent.com/82949084/223722597-57b3df32-23c4-4abd-af39-647065f8254f.png">

Link to concave hull example
https://github.com/SanyM/ConcaveHull

now while there are packages like the above that support concave hull it would be nice to be able to solve the problem with less dependencies if possible.

**Comment by macdrevx** [comment]
Apologies for my confusion. It looks like concave hull is new in geos 3.11. GEOSwift is currently on 3.10. We'll add concave hull after we update. (hopefully soon!)

**Comment by alessdiimperio** [comment]
🤞 here's hoping :)
great work with the framework

**Comment by macdrevx** [comment]
@alessdiimperio @vladislavitsi concave hull is now available on the main branch. Please give it a try and let me know if it looks okay!

**Comment by macdrevx** [comment]
I released the changes in v10: https://github.com/GEOSwift/GEOSwift/releases/tag/10.0.0

I don't have any examples, but the release notes at that link show the method name. You just invoke it on any geometry.

**Comment by alessdiimperio** [comment]
having issue if trying to have GEOSwiftMapKit as well ass v.10 of GEOSwift.
Are they not compatible?

**Comment by macdrevx** [comment]
@dr-jts could you please advise here?

**Comment by dr-jts** [comment]
Perhaps the `GEOSMakeValid` function could help here?  Note that this probably needs the `GEOS_MAKE_VALID_STRUCTURE ` method (use [`GEOSMakeValidWithParams`](http://libgeos.org/doxygen/geos__c_8h.html#ad378f6774219e39a87f46f4d2fa3e770) to specify this).

For a full explanation see https://lin-ear-th-inking.blogspot.com/2021/05/fixing-invalid-geometry-with-jts.html

**Comment by macdrevx** [comment]
Thank you! @alessdiimperio, we expose only GEOSMakeValid (`makeValid()` on any `GeometryConvertible`) right now, but we'd be happy to expose `GEOSMakeValidWithParams` as well. Would you mind opening a new issue to track that?
