### ISSUE TITLE
Support for fixing invalid geometries with GeometryFixer/GEOSMakeValidWithParams

### ISSUE THREAD

**Issue by alessdiimperio** [GEOSwift/GEOSwift#259]
Could you expose a function to support GEOSMakeValidWithParams so invalid Geometries can be fixed example excluding lines that intersect.

![bild](https://user-images.githubusercontent.com/82949084/231559961-2684b398-0668-42d6-b8d3-2205102b170e.png)
![bild](https://user-images.githubusercontent.com/82949084/231559984-0122835a-c3c6-4e30-a309-515357784c3e.png)

[related issue](https://github.com/GEOSwift/GEOSwift/issues/256)

**Comment by macdrevx** [comment]
@alessdiimperio I pushed an implementation to the main branch. Could you try it out and let me know what you think?

**Comment by alessdiimperio** [comment]
worked beautifully!
great work!

**Comment by macdrevx** [comment]
Thanks for testing it. I just released a new version 10.1.0 with this change! It's not out on CocoaPods yet — I'm running into an [issue](https://github.com/CocoaPods/CocoaPods/issues/11621) when trying to push. I'll try again tonight.
