### ISSUE TITLE
Getting at coordinates after a Polygon is buffered

### ISSUE THREAD

**Issue by gwall-ceres** [GEOSwift/GEOSwift#262]
I recently upgraded the version of GEOSwift in my project to the latest build from version 4.1.0.
I am trying to figure out how to buffer a polygon object and then save it to something that can be displayed using mapkit.

Here's the old code for reference:

```swift
func initInflatedPolygon() {
        var geosCoords = [Coordinate]()
        //copy the coordinates into the GEOSwift coordinate type
        for coord in self.coordinates {
            geosCoords.append(Coordinate(coord))
        }
        
        if geosCoords.count > 1 {
            //the first and last coordinate have to be the same for the linear ring class
            if geosCoords.first != geosCoords.last {
                geosCoords.append(geosCoords.first!)
            }
        }
        let linearRing = LinearRing(points: geosCoords)!
        let geosPoly : Polygon = Polygon(shell: linearRing, holes: nil)!
        //the magic happens here to buffer the polygon
        let geosGeom = geosPoly.buffer(width:bufferWidthDeg)
        //get the map shape and cast to Mapkit Polygon
        let mkPoly = geosGeom?.mapShape() as! MKPolygon
        let coords = mkPoly.getGeoCoords()
        //store the inflated polygon internally in this objectt
        self.inflatedPolygon = StyledPolygon(coordinates: coords, count: coords.count)
    }
```

I realize I need to install the new support library, GEOSwiftMapKit.
But I am still struggling to convert the object I get once I call the buffer method into something I can display with mapKit.

Here is the updated code, but I can't figure out how to get at the coordinates or Polygon object after the call to buffer happens.
```swift
  func initInflatedPolygon() {
        var geosCoords = [Point]()
        
        for coord in self.coordinates {
            geosCoords.append(Point(coord))
        }
        
        if geosCoords.count > 1 {
            //the first and last coordinate have to be the same for the linear ring class
            if geosCoords.first != geosCoords.last {
                geosCoords.append(geosCoords.first!)
            }
        }
 
        let linearRing = try! Polygon.LinearRing(points: geosCoords)
        let geosPoly = Polygon(exterior: linearRing, holes: [])
        let bufferedPoly = try! geosPoly.buffer(by:bufferWidthDeg)
        //how do I get the coordinates out of the bufferPoly?
        let coords = bufferedPoly.getCoords() //this is not a real method, but this is what I want
        self.inflatedPolygon = StyledPolygon(coordinates: coords, count: coords.count)
    }
```

**Comment by macdrevx** [comment]
Happy to help!

If you haven't already seen it, check out https://github.com/GEOSwift/GEOSwift/blob/2d23ede8c82c067655d3a9f0221bc73f08cd399a/VERSION_5.md which describes the rewrite that happened in 2019. There have been more new versions since then, but what we have today in v10 is iteration on that rewrite.

`buffer(by:)` [returns](https://github.com/GEOSwift/GEOSwift/blob/2d23ede8c82c067655d3a9f0221bc73f08cd399a/Sources/GEOSwift/GEOS/GeometryConvertible%2BGEOS.swift#L409) a `Geometry`. `Geometry` is an [enum](https://github.com/GEOSwift/GEOSwift/blob/2d23ede8c82c067655d3a9f0221bc73f08cd399a/Sources/GEOSwift/Core%20Types/Geometry.swift).

To extract the coordinates, you could use a switch case let…

```
switch bufferedPoly {
case .polygon(let polygon):
    // now we have a Polygon which provides easy access to the underlying points:
    polygon.exterior.points // for the exterior ring
    for hole in polygon.holes {
        hole.points // for the points of each hole
    }
default:
    // … you can decide what to do for other result types …
    break
}
```

I hope that helps!

**Comment by gwall-ceres** [comment]
Wow! Thanks so much!

**Comment by macdrevx** [comment]
@gwall-ceres it sounds like this is resolved for you, but if not feel free to reopen.
