### ISSUE TITLE
Compiling with Xcode 15.0 beta 5 for "My Mac (Mac Catalyst)" fails with "ld: Undefined symbols:..."

### ISSUE THREAD

**Issue by GerdC** [GEOSwift/GEOSwift#268]
Reproduce:
Compile a project that uses GeoSwift with Xcode 15.0 beta 5 for "My Mac (Mac Catalyst)"

Result:
In the build, the link step for geos fails:

```
ld: Undefined symbols:
  ___llvm_profile_runtime, referenced from:
      ___llvm_profile_runtime_user in geos.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by macdrevx** [comment]
Possibly related to https://github.com/GEOSwift/geos/issues/14. Do you have code coverage enabled? If so, could you try turning it off to see whether that makes this error go away?

**Comment by GerdC** [comment]
Yes , disabling code coverage in all test plans makes the error go away.
(I had no problem with other targets, including "My Mac (designed for iPad)")

**Comment by macdrevx** [comment]
Duplicates https://github.com/GEOSwift/geos/issues/14
