### ISSUE TITLE
Please enable third elevation value for Points

### ISSUE THREAD

**Issue by EugeneNaloiko** [GEOSwift/GEOSwift#272]
According to GeoJSON standard the Points are [x, y] or [x, y, z]. Elevation, in meters, https://datatracker.ietf.org/doc/rfc7946/ is an optional third number.

**Comment by macdrevx** [comment]
Thanks for the feature request. I'm going to merge this into the existing tracking issue #252.

Could you say more about your use case?

I don't think we have a clear idea yet of how we'd model the optional z. Would we extend `Point` with another property of type `Double?`? Would we add an entire parallel set of geometry types that all have z coordinates? How would this impact interactions with GEOS? Would we need to restrict certain operations to only work with [x, y] or [x, y, z]?

It's definitely a capability worth investigating, but it would take some work to figure out how to do it without making the existing developer experience worse for folks who only need [x, y]
