### ISSUE TITLE
How to split polygon with a line?

### ISSUE THREAD

**Issue by valvarezf** [GEOSwift/GEOSwift#276]
I know this was an old issue (https://github.com/GEOSwift/GEOSwift/issues/139), but I don't know how to split a polygon with a line using the last version of geos (3.12.2) with c++.

I tried several methods:
.- OverlayNG::overlay DIFFERENCE
.- intersection and then add intersection and polygon to a polygonizer
.- symdifference / difference
.- intersection and then difference / symdifference
.- intersection and then EnhancedPrecisionOp::difference / EnhancedPrecisionOp::symdifference
.- intersection and then add intersection and polygon to a geomcollection and then use polygonizer

Two or three aditional methods I can't remember know.

Can someone help me?

**Comment by macdrevx** [comment]
Sounds like you're using the C++ API and not this Swift API? If so, please head over to https://github.com/libgeos/geos which is the home for the C++ API.
