### ISSUE TITLE
Polygon.buffer draws not accurate buffer (geometry)

### ISSUE THREAD

**Issue by NickolaAndriiev** [GEOSwift/GEOSwift#277]
I noticed that Polygon.buffer generates an inaccurate buffered polygon. 
I have a polygon, and I'm trying to create a 300m buffer around it. 
While the resulting polygon has an accurate vertical distance of ±300m, the horizontal distance is only 222m.

I tried different shapes an everywhere horizontal distance is less then needed

I used the C++ GEOS library in my Swift project, and when I noticed this issue, I tried using GEOSwift in a pet project, but I got the same result.

![Vertical](https://github.com/user-attachments/assets/c827f4cb-f147-4a8f-aed1-cc25361be857)![Horizontal](https://github.com/user-attachments/assets/b715d4f3-10ea-439b-afe8-024e115c1870)
![Test](https://github.com/user-attachments/assets/8f0027cb-8e19-469f-b801-26ebbfb3de6c)

**Comment by macdrevx** [comment]
Closing in favor of #278
