### ISSUE TITLE
Polygon.buffer draws not accurate buffer (geometry) 

### ISSUE THREAD

**Issue by NickolaAndriiev** [GEOSwift/GEOSwift#278]
I noticed that Polygon.buffer generates an inaccurate buffered polygon.
I have a polygon, and I'm trying to create a 300m buffer around it.
While the resulting polygon has an accurate vertical distance of ±300m, the horizontal distance is only 222m.

I tried different shapes an everywhere horizontal distance is less then needed

I used the C++ GEOS library in my Swift project, and when I noticed this issue, I tried using GEOSwift in a pet project, but I got the same result.

![Vertical](https://github.com/user-attachments/assets/e3bc56a7-d134-4437-972a-5b50b333bd1e)![Horizontal](https://github.com/user-attachments/assets/6d3d36bb-547d-46ba-b779-4e9f382b51cb)

**Comment by NickolaAndriiev** [comment]
I would share whole test project "Buffer" which builds 0.05 buffer around polygon. 
It's clear that horizontal distance is not accurate (25% less the vertical)

![Test](https://github.com/user-attachments/assets/b75d8375-fddd-43c9-b371-6719ef4f1d11)

[Buffer.zip](https://github.com/user-attachments/files/16814659/Buffer.zip)

**Comment by NickolaAndriiev** [comment]
Regarding your question, it seems that function `buffer(by width: Double)` takes `latitude degree` as a width.
So I use the next logic to convert meters in `latitudeDegree`

func latitudeDegree(measurement: Measurement<UnitLength>) -> Double {
        let meters = measurement.converted(to: .meters).value
        return latitudeDegree(meters: meters)
}
    
/// Convert distance in meters to latitude degree
private func latitudeDegree(meters: CLLocationDistance) -> Double {
        let r: CLLocationDistance = 6378137.0 //earth radius
        return meters / r * (180 / Double.pi)
}

**Comment by macdrevx** [comment]
I took the example you shared and simplified it to this:

```
import UIKit
import GEOSwift
import CoreLocation

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let coordinates = [
            CLLocationCoordinate2D(latitude: 37.773972, longitude: -122.431297), // Point 1
            CLLocationCoordinate2D(latitude: 37.784443, longitude: -122.439239), // Point 2
            CLLocationCoordinate2D(latitude: 37.792456, longitude: -122.425678), // Point 3
            CLLocationCoordinate2D(latitude: 37.780838, longitude: -122.412241), // Point 4
            CLLocationCoordinate2D(latitude: 37.768842, longitude: -122.422003),  // Point 5
            CLLocationCoordinate2D(latitude: 37.773972, longitude: -122.431297)
        ]

        let points = coordinates.map { Point(x: $0.longitude, y: $0.latitude) }

        let polygon = try! Polygon(exterior: Polygon.LinearRing(points: points))
        let bufferedGeometry = try! polygon.buffer(by: 0.05)!

        print("input")
        print(polygon.exterior.points.map { "\($0.x),\($0.y)" }.joined(separator: "\n"))

        if case let .polygon(bufferedPolygon) = bufferedGeometry {
            print("buffered polygon")
            print(bufferedPolygon.exterior.points.map { "\($0.x),\($0.y)" }.joined(separator: "\n"))
        }
    }
}
```

I took the output and plotted it on a grid: https://www.desmos.com/calculator/mhq4hsncnh

<img width="982" alt="Screenshot 2024-09-03 at 10 39 07 AM" src="https://github.com/user-attachments/assets/74351442-f964-406f-85c8-cc9e231297bf">

As you can see, the amount of buffer is 0.05, as expected.

You may need to double check your conversions from length to latitude.

**Comment by NickolaAndriiev** [comment]
@macdrevx 
Thank you! I believe I understand the problem:

1. I need to convert (latitude, longitude) into a 2D coordinate space (for example, using mercatorProjection).
2. Build a buffered polygon.
3. Convert the resulting polygon from the 2D coordinate space back into 3D Earth coordinate space (using the inverse of mercatorProjection).
