### ISSUE TITLE
Xcode 16 crash when using polygonize()

### ISSUE THREAD

**Issue by danielnkv** [GEOSwift/GEOSwift#280]
I have an app where I'm using `polygonize() on `Polygon.LinearRing` object. This was working as expected on Xcode 15 debug/release build.

With Xcode 16 it works on debug release but when I builded for release I start getting following crashes from users.

Any suggestions? Thanks.

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000a07337126a78

Crashed: com.apple.main-thread
0  geos                           0xd49a4 geos::operation::polygonize::Polygonizer::add(geos::geom::Geometry const*) + 8
1  geos                           0xcaa8 GEOSPolygonize_r + 76
2  App                         0x6b174c Collection<>.polygonize() + 456 (GeometryConvertible+GEOS.swift:456)
3  App                         0x6b14a4 GeometryConvertible.polygonize() + 404 (GeometryConvertible+GEOS.swift:404)
```

**Comment by danielnkv** [comment]
I fixed my issue. Instead of `polygonize()` I used `geometry` property of the `LinearRing` object.

But maybe it should be checked why `polygonize()` crashes on Release build with Xcode 16

**Comment by macdrevx** [comment]
Reproducible with GEOSwift 10.3.0 in a fresh iOS app project created with Xcode 16.0 building in release mode using the following:

```
let ring = try! Polygon.LinearRing(points: [
            .init(x: 0, y: 0),
            .init(x: 1, y: 0),
            .init(x: 1, y: 1),
            .init(x: 0, y: 1),
            .init(x: 0, y: 0),
        ])

        let polygon = try! ring.polygonize()
```

**Comment by danielnkv** [comment]
Sorry for my late response. 

Thanks for the quick fix!
