### ISSUE TITLE
swift 6

### ISSUE THREAD

**Issue by wibed** [GEOSwift/GEOSwift#287]
any intention on upgrading to swift 6.

if not why? and what is preventing you from doing so.

**Comment by macdrevx** [comment]
Hi @wibed, thanks for asking. The latest release of GEOSwift should compile without any issues using the Swift 6 compiler (in swift 5 language mode). For now, I've not upgraded the package to use the Swift 6 language mode to preserve compatibility with Xcode 15 (which has the Swift 5.9 compiler). In the past, Apple has typically started requiring the latest Xcode sometime around April of the following year ([example](https://developer.apple.com/news/?id=fxu2qp7b)), and if they follow the same schedule for Xcode 16, then I'll update the package to use Swift 6 language mode sometime after that.

At any rate, the package already builds without issues in Swift 6 language mode, so if you did need that for some reason, feel free to fork the repo and update the package manifest.

Out of curiosity, how would configuring GEOSwift to build with Swift 6 language mode help your project?

**Comment by wibed** [comment]
hi, no improvement in particular. 
i am saddened to not give a more suitable response.

it has been quite informative.
