### ISSUE TITLE
GeoSwift for Mac App développement

### ISSUE THREAD

**Issue by Abd3L** [GEOSwift/GEOSwift#36]
I have some troubles to build the GeoSwift Framework for OS X. Can any one help please.

**Comment by vfn** [comment]
@Abd3L can you please post the error logs here?

**Comment by Abd3L** [comment]
Thanks @vfn 

Ld /Users/abdellahichiba/Documents/Debug/ChartTest.app/Contents/MacOS/ChartTest normal x86_64
    cd /Users/abdellahichiba/Desktop/FINAL_RAINFALL_MODULE/Essaie_Code/ChartTest
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/abdellahichiba/Documents/Debug -F/Users/abdellahichiba/Documents/Debug -filelist /Users/abdellahichiba/Documents/ChartTest.build/Debug/ChartTest.build/Objects-normal/x86_64/ChartTest.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/abdellahichiba/Documents/ChartTest.build/Debug/ChartTest.build/Objects-normal/x86_64/ChartTest_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -add_ast_path -Xlinker /Users/abdellahichiba/Documents/ChartTest.build/Debug/ChartTest.build/Objects-normal/x86_64/ChartTest.swiftmodule /Users/abdellahichiba/Documents/Debug/GEOSwift.framework/GEOSwift -Xlinker -dependency_info -Xlinker /Users/abdellahichiba/Documents/ChartTest.build/Debug/ChartTest.build/Objects-normal/x86_64/ChartTest_dependency_info.dat -o /Users/abdellahichiba/Documents/Debug/ChartTest.app/Contents/MacOS/ChartTest

clang: error: no such file or directory: '/Users/abdellahichiba/Documents/Debug/GEOSwift.framework/GEOSwift'

**Comment by Abd3L** [comment]
Showing Recent Issues
Target 'GEOSwift' of project 'GEOSwift' was rejected as an implicit dependency for 'GEOSwift.framework' because it doesn't contain platform 'macosx' in its supported platforms 'iphonesimulator, iphoneos'

**Comment by vfn** [comment]
Interesting, the docs say that it supports macOS, but the project does not have a macOS target. Feel free to add macOS support and create a PR

**Comment by macdrevx** [comment]
Proposed version 5 add support for macOS and is now up for review: #167 

Please let me know if you have any feedback.

**Comment by macdrevx** [comment]
macOS support now available in version 5.0.0
