### ISSUE TITLE
intersection not reported correctly

### ISSUE THREAD

**Issue by biomiker** [GEOSwift/GEOSwift#38]
I think I've encountered a problem with the intersection function.  See sample code and output below.  I compute two intersections with a LinearRing, one for each of two LineStrings (l1 and l2).  The intersection method returns a single point for l1 (let's call it p1) and no intersection for l2.  However, as you can see in the output, the first point of l2 has the exact same coordinates as p1!!  Since p1 is on the polygon and is also on l2, shouldn't it be returned by the call to intersection between l2 and the polygon?  

Output:
```
------------------------------
LINESTRING (-93.22021411377627 41.02901854527665, -93.21658311574629 41.03020949145205)
INTERSECTION WITH POLYGON:
     POINT (-93.21758591425403 41.02988057939051)
------------------------------
LINESTRING (-93.21758591425403 41.02988057939051, -93.22099602915671 41.02797278078819)
INTERSECTION WITH POLYGON:
     GEOMETRYCOLLECTION EMPTY
```

Code:
```
    func showIntersectionError() {
        let wkt = "LINEARRING (-93.22013091198183 41.02908541733761, -93.22119394432185 41.02823102274288, -93.21985273529471 41.02648097815198, -93.2194752097908 41.02827599115583, -93.21617682907213 41.02745531278529, -93.21605761049196 41.02948263210197, -93.21715044747705 41.02926528847117, -93.21777634502303 41.03014964773079, -93.21703122889683 41.03079417326732, -93.22013091198183 41.02908541733761)"
        
        guard let pgon = Geometry.create(wkt) as? LinearRing else {
            print("Can't create polygon")
            return
        }

        let l1 = LineString.create("LINESTRING (-93.22021411377627 41.02901854527665, -93.21658311574629 41.03020949145205)") as! LineString
        let l2 = LineString.create("LINESTRING (-93.21758591425403 41.02988057939051, -93.22099602915671 41.02797278078819)") as! LineString
        
        for l in [ l1, l2 ] {
        
            let i = l.intersection(pgon)

            print("------------------------------")
            print(l.WKT ?? "")
            print("INTERSECTION WITH POLYGON:\n    ", i.WKT ?? "")
            
        }
    }

```

**Comment by robbroadwell** [comment]
I have the same issue. Intersection() returns the first polygon provided to it.

**Comment by macdrevx** [comment]
@biomiker @robbroadwell closing this issue since it's been a couple years. If it's still something you'd like to solve, could you please re-open? I'd also be interested to hear whether it's still an issue in GEOSwift 5. Chances are the behavior you're seeing is from geos since GEOSwift (especially pre-v5) is just a thin wrapper around that library.
