### ISSUE TITLE
Return nil for the whole Geojson

### ISSUE THREAD

**Issue by Pr0gmaT1k** [GEOSwift/GEOSwift#41]
Return nil for the whole geojson if only one of the geometry in feature collection failed to load.

Exactly here:
https://github.com/andreacremaschi/GEOSwift/blob/486873afb7c5f354af5936fa15fe2ca23f667ae0/GEOSwift/GeoJSON.swift#L100

**Comment by vfn** [comment]
What would the correct behaviour be? Ignore errors? Throw exceptions?

**Comment by Pr0gmaT1k** [comment]
add error inside GEOJSONParseError and throw + trace would be a good first solution.
In another step, my geojson load without any error with geojson.io, it would be a good idea to find why he throw errors. I will investigate.

**Comment by macdrevx** [comment]
Proposed version 5 supports Codable and is now up for review: #167 

This may address some of your concerns about more helpful error messages. Please let me know if you have any feedback.

**Comment by macdrevx** [comment]
Version 5 now available.
