### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by twof** [GEOSwift/GEOSwift#42]
Are there any plans to support swift package manager?

**Comment by twof** [comment]
Nevermind. Found https://swiftmodules.com/petrpavlik/geoswift
Though you might want to add that to the readme

**Comment by vfn** [comment]
Hey Alex,

It would be awesome if you could create a PR to merge the changes required to add package manager support.

**Comment by twof** [comment]
Made the changes to the readme #43

**Comment by vfn** [comment]
@twof that library has nothing to do with GEOSwift. It only adds a way to calculate the distance in between 2 coordinates.

**Comment by twof** [comment]
Yup. I just had someone else point out that that was a completely different repo. My bad. I'm in the middle of going over how to bring this to SPM right now.

**Comment by vfn** [comment]
That's awesome @twof! Thank you for helping with that.

**Comment by twof** [comment]
Okay so the problem I'm having is that GEOSwift relies on geos which is also not on SPM. To compound that, geos isn't on github, and it's also in C++ rather than Swift so I'm not sure how I'd go about getting that on SPM. If anyone has any thoughts as to a resolution, I'm all ears.

**Comment by vfn** [comment]
You can get GEOS from https://github.com/OSGeo/geos/blob/svn-trunk/README.md

And this might help you getting the C++ code into a swift package http://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/

**Comment by macdrevx** [comment]
Support was added in #131 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
