### ISSUE TITLE
Failed to build on xcode 9

### ISSUE THREAD

**Issue by idanaviv10** [GEOSwift/GEOSwift#55]
I am trying to add GEOSwift to xcode 9, I am using swift version 3.2, and when I build it I get an error:

Showing Recent Issues
-1: **unable to build node**: '/Users/idanaviv/Library/Developer/Xcode/DerivedData/Mapit-bzfzfkmrqlfkroczgpyrzczwflze/Build/Products/Debug-iphonesimulator/GEOSwift/GEOSwift.framework/Info.plist' (**node is produced by multiple commands**; e.g., '88b8ceef99a0f83e40520894e5900ab26746848abd41793ca5ed3c9d64e390f4:CopyPlistFile /Users/idanaviv/Library/Developer/Xcode/DerivedData/Mapit-bzfzfkmrqlfkroczgpyrzczwflze/Build/Products/Debug-iphonesimulator/GEOSwift/GEOSwift.framework/Info.plist /Users/idanaviv/programming/Mapit/Pods/GEOSwift/GEOSwift/Info.plist' **and** '88b8ceef99a0f83e40520894e5900ab26746848abd41793ca5ed3c9d64e390f4:ProcessInfoPlistFile /Users/idanaviv/Library/Developer/Xcode/DerivedData/Mapit-bzfzfkmrqlfkroczgpyrzczwflze/Build/Products/Debug-iphonesimulator/GEOSwift/GEOSwift.framework/Info.plist /Users/idanaviv/programming/Mapit/Pods/Target Support Files/GEOSwift/Info.plist')

**Comment by vfn** [comment]
Hi Idan,

I have added a swift4 branch that should compile on Xcode 9.

Please checkout that one and let me know if you have any issues.

If you do find issues, please create a sample project

Thanks!

**Comment by idanaviv10** [comment]
Hi,
Thank  you for the quick response,  I tried the swift 4 branch and it still didn't work. 
But I think it might be xcode bug. When I change the build system form "New Build System" to the "Default" it works fine.

If you want to reproduce this problem, just have a empty xcode project add the cocoapods, change it to the new build system( File -> Workspace Setting -> Build System: "New Build System(preivew)"). 
- In my Project I am using about 10 other dependencies, and they all work fine with the new build system, and the only one that don't build is the "GEOSwift".

Thanks !

**Comment by vfn** [comment]
Hi @idanaviv10,

I have just published a new version of the pod. The issue highlighted by the new build system showed that we were including the `Info.plist` file as a source file. The podspec was telling cocoapods to grab anything inside the source folder.

It was a minor change https://github.com/GEOSwift/GEOSwift/commit/95454834f2904840a377f3e4cab3e2c81e277e9a
```
-  s.source_files = "GEOSwift/*"
 +  s.source_files = "GEOSwift/*.{swift,h}"
```

I'm closing this issue. Let me know if you still have problems with it.
