### ISSUE TITLE
Getting odd output from swiftCallback??

### ISSUE THREAD

**Issue by ssokol** [GEOSwift/GEOSwift#59]
I'm using the library with Swift 3 on iOS 10.3.2. Everything seems to be working correctly, but I keep getting odd messages in the debug output:

```
GEOSwift # %s.
GEOSwift # %s.
GEOSwift # %s.
GEOSwift # %s.
```

Looks like that is coming from the swiftCallback function, defined at the top of GEOS.swift:

```
let swiftCallback : GEOSCallbackFunction = { args -> Void in
    if let string = String(validatingUTF8: args.assumingMemoryBound(to: CChar.self)) {
        print("GEOSwift # " + string + ".")
    }
}
```

Does this indicate any sort of error? If not, is it acceptable if I comment out the print statement?

Thanks!

**Comment by vfn** [comment]
Hi @ssokol, That appears to be debug code.

Could you please create a pull request wrapping it on a check for `DEBUG`?

```
#if DEBUG
    print("GEOSwift # " + string + ".")
#endif
```

Thanks!

**Comment by ssokol** [comment]
Done. Thanks!

**Comment by vfn** [comment]
Merged https://github.com/GEOSwift/GEOSwift/pull/60

Thanks @ssokol!
