### ISSUE TITLE
GEOJSON from String or json resource

### ISSUE THREAD

**Issue by jketch836** [GEOSwift/GEOSwift#62]
Hey there. I'm having an issue and was wondering if GeoSwift can create a MultiPolygon from a string or a json url. Specifically I am getting a shape from a json source that is listed below.
"shape": [
  [
   [
    [ -84.321797, 34.988965 ],
    [ -84.308201, 35.092843 ],
    [ -84.30696, 35.106162 ],
    [ -84.297721, 35.169478 ],
    [ -84.294723, 35.185594 ],
    [ -84.29024, 35.225572 ],
    [ -84.289921, 35.225585 ],
    [ -84.290061, 35.225257 ],
    [ -84.289621, 35.224677 ],
    [ -84.288516, 35.224391 ],
    [ -84.28712, 35.224877 ],
    [ -84.28512, 35.226577 ],
    [ -84.28322, 35.226577 ],
    [ -84.28152, 35.229277 ],
    [ -84.27792, 35.231477 ],
    [ -84.27702, 35.233177 ],
    [ -84.27662, 35.233277 ],
    ... truncated ..
   ],
   ... truncated ...
  ]
 ]
any thoughts?

**Comment by vfn** [comment]
Hi @jketch836 GEOSwift has support to geometries represented by a [GeoJSON](https://en.wikipedia.org/wiki/GeoJSON) or [WKT](https://en.wikipedia.org/wiki/Well-known_text).
