### ISSUE TITLE
Cannot get my code to produce an MKPolyline, only MKShape.

### ISSUE THREAD

**Issue by alexahlen** [GEOSwift/GEOSwift#63]
Sorry to post this here, but this is the only place where someone might be able to help.

I cant seem to get an MKPolyline out of the function, it always returns an MKShape. Is the correct behaviour? Ive read through the codebase and as far as i understand it it should return a MKPolyline? 

Here is my code (this returns the error:  Cannot invoke 'add' with an argument list of type '(MKShape)'):

`                let linestring = LineString(WKT: "LINESTRING(51.063164 -0.728986, 51.072347 -0.723721, 51.116898 -0.731893)")
                let shapeLine = linestring!.mapShape()
                self.mapView.add(shapeLine)`

If i force downcast it runs, but i still get no polyline:

`                let linestring = LineString(WKT: "LINESTRING(51.063164 -0.728986, 51.072347 -0.723721, 51.116898 -0.731893)")
                let shapeLine = linestring!.mapShape()
                dump(shapeLine)
                let shapePoly = shapeLine as! MKPolyline
                self.mapView.add(shapePoly)`

I am sure this is incredibly simple, but i cant seem to work out where i am going wrong. Any help would be extremely appreciated.

Alex

Here is the same question i posted on stackoverflow 3 days ago:
https://stackoverflow.com/questions/47342588/require-mkpolyline-but-code-keeps-returning-mkshape
(i wouldnt usually post in multiple places)

**Comment by vfn** [comment]
@alexahlen I have answered you question on [SO](https://stackoverflow.com/a/47391712/227148).

All you need to do is to downcast shapeLine to a MKPolyline

```Swift
guard let shapeLine = linestring.mapShape() as? MKPolyline else {
    preconditionFailure()
}
```
