### ISSUE TITLE
Problem trying to display MultiPolygon as an overlay

### ISSUE THREAD

**Issue by joeuelk** [GEOSwift/GEOSwift#66]
[multipolygon.geojson.zip](https://github.com/GEOSwift/GEOSwift/files/1508236/multipolygon.geojson.zip)

In the code below the line `if let geo = geometries?[0] as? MultiPolygon {` is giving me the following error:

`Generic parameter 'T' count not be inferred in case to 'MultiPolygon<_>'`

Xcode 8.3 prompts me to change `MultiPolygon` to `MultiPolygon<Polygon>` but execution never makes it past this 'if' statement when I update it. 

Any ideas? I'm relatively new to Swift.

Thank you!

```
func addOverlay() {
    if let geoJSONURL = Bundle.main.url(forResource: "multipolygon", withExtension: "geojson") {
        do {
            let geometries = try Geometry.fromGeoJSON(geoJSONURL)
            if let geo = geometries?[0] as? MultiPolygon {
                if let shapesCollection = geo.mapShape() as? MKShapesCollection {
                    let shapes = shapesCollection.shapes
                    for shape in shapes {
                        if let polygon = shape as? MKPolygon {
                            mapView.add(polygon)
                        }
                    }
                }
            }
        } catch {
            print("Unable to load geojson data")
        }
    }
}
```

**Comment by vfn** [comment]
Hi @joeuelk,

We ddi some changes not so long ago to add support for features, and I didn't realise that it need more changes to make it clear what `Geometry.fromGeoJSON` actually returns.

It will return an array of features, that may contain geometries inside it.

please try the following:

```
...
if let geoJSONURL = Bundle.main.url(forResource: "multipolygon", withExtension: "geojson") {
        do {
                let features = try Geometry.fromGeoJSON(geoJSONURL)
                if let geo = features?.first?.geometries?.first as? MultiPolygon<Polygon> {
...
```

**Comment by joeuelk** [comment]
Thanks much for the quick response. I think that did it!

Now I'm on to figuring how how to make the overlay actually appear on the map.

**Comment by vfn** [comment]
No problems!

You'll need an overlay renderer for that. You add the overlay to the map and then provide a renderer for it, via the delegate method

```
func mapView(_ mapView: MKMapView, rendererFor overlay: MKOverlay) -> MKOverlayRenderer
```
