### ISSUE TITLE
Playground - Ambiguous reference to member 'subscript'

### ISSUE THREAD

**Issue by hansen-m** [GEOSwift/GEOSwift#70]
When running the included playground I get the following error:

`Ambiguous reference to member 'subscript'`

Related to line 79, which is:

`let italy = geometries[0] as? MultiPolygon`

Did I miss something?

**Comment by vfn** [comment]
@hansen-m Thank you for raising this issue. I have pushed some changes and published a new version of the pod (2.1.1).

https://github.com/GEOSwift/GEOSwift/compare/2.1.0...2.1.2
