### ISSUE TITLE
Errors in Xcode 9: Geometry has no member geometries

### ISSUE THREAD

**Issue by joeuelk** [GEOSwift/GEOSwift#73]
I'm getting an error in Xcode 9.2 / Swift 4 on a project that was working in Xcode 8.

```
func addOverlay(url:URL?) {
        if let geoJSONURL = url {
            do {
                let features = try Geometry.fromGeoJSON(geoJSONURL)
                if let geo = features?.first?.geometries?.first as? MultiPolygon<Polygon> {
```

The following errors with "Geometry has no member geometries":
`if let geo = features?.first?.geometries?.first as? MultiPolygon<Polygon> {`

And this warns about being deprecated:
`let features = try Geometry.fromGeoJSON(geoJSONURL)`

But when I switch it to the suggestion:
`let features = try Geometry.Features.fromGeoJSON(geoJSONURL)`

It errors with "Geometry has no member Features".

Any ideas?

Thanks!

**Comment by joeuelk** [comment]
Looks like this is working:

```
func addOverlay(url:URL?) {
        if let geoJSONURL = url {
            do {
                let features = try Geometry.fromGeoJSON(geoJSONURL)
                if let geo = features?.first as? MultiPolygon<Polygon> {
```

But it's still complaining about this being deprecated:
`let features = try Geometry.fromGeoJSON(geoJSONURL)`

**Comment by vfn** [comment]
Hi @joeuelk,

The readme file was out of date. I have just updated it to match the api changes. The code on the playground file is up to date, and you can use it as a guide.

The deprecation notice is defined at https://github.com/GEOSwift/GEOSwift/blob/feb5124f1a758ac8162fdf0adb06065de897d07e/GEOSwift/GeoJSON.swift#L22 and it points to the new function to be used instead.

The `fromGeoJSON` method is now part of `Features` as it return features, and geometries can be found within them

```
if let geoJSONURL = url,
    let features = try! Features.fromGeoJSON(geoJSONURL),
    let geo = features.first?.geometries?.first as? MultiPolygon {
...
}
```

**Comment by joeuelk** [comment]
Thanks much for the explanation
