### ISSUE TITLE
GEOSwift # TopologyException: side location conflict at 8.6666822676303692 49.6224086061181.

### ISSUE THREAD

**Issue by funkenstrahlen** [GEOSwift/GEOSwift#74]
[I use this geojson](https://gist.github.com/90289f724574a5fc5c6b1b97b7a44b0a). It contains geometries (polygons and multi polygons) marking regions in Germany.

I want to find out in with region (geometry) a specific map location is contained in.

This is what I do (shortened at some places)

```swift
    public func regionIdFor(location: CLLocationCoordinate2D) -> (regionId: Int?, partregionId: Int?) {
        guard let features = try? Features.fromGeoJSON(GeoHelper.geoJSONURL) else { return (nil, nil) }
        guard let wayPoint = Waypoint(latitude: location.latitude, longitude: location.longitude) else { return (nil, nil) }
        for region in features! {
            if let regionGeometry = region.geometries?.first {
                // check if user location is within the region
                if regionGeometry.contains(wayPoint) {
                    // GF is the partregion id
                    guard var partregionId = region.properties?.value(forKey: "GF") as? Int else { return (nil,nil) }
                    print(partregionId)
//                    return (regionId, partregionId)
                }
            }
        }
        return (nil, nil)
    }
```

For some locations I see the error in my terminal:
```
GEOSwift # TopologyException: side location conflict at 8.6666822676303692 49.6224086061181.
```

Every time this error occurs the function above finds multiple containing geometries. However this should not be possible because when I display the regions on the map they do not overlap at all.

Why does this happen?

**Comment by funkenstrahlen** [comment]
I use the `geos` `isValid()` function to find out that one of the polygons in the geojson is invalid. Its the one:

```
      "geometry_name": "THE_GEOM",
      "properties": {
        "GF": 111,
        "GEN": "Oberrhein und unteres Neckartal",
        "DES": "Pollenfluggebiet",
        "bbox": [
          7.51140615808012,
          47.5773391340742,
          9.17334188771982,
          49.6252264420181
        ]
      }
```

How can I find out what's wrong with it? How can I fix it?

**Comment by funkenstrahlen** [comment]
I could find the bug in the geojson.

I added this to the Geometry extension, maybe this is also a good idea to add to the code of this repo:

```swift
    func isValid() -> Bool  {
        let isValid = GEOSisValid_r(GEOS_HANDLE, self.geometry)
        return isValid == 1
    }
```

**Comment by vfn** [comment]
@funkenstrahlen, good job! That was a nice detective work.

Could you create a PR adding the `isValid` property and some tests.

Cheers!

**Comment by funkenstrahlen** [comment]
I see what I can do. But might take some time.
