### ISSUE TITLE
Features.fromGeoJSON fails if there is a feature with null geometry

### ISSUE THREAD

**Issue by Tybion** [GEOSwift/GEOSwift#76]
This feature (within a file with a list of features, produced by ogr2ogr) causes .fromGeoJSON to return a nil.  It does not seem to throw an error.

{ "type": "Feature", "properties": { "gml_id": "dw_drillhole_full_pet.fid-618ffdfe_161c6b53f05_-1767", "project": "MIN", "site_id": "043786", "confidential": false, "bus_purpose": "Stratigraphic Test", "show_yn": true, "program": "Cobar Aircore End of Hole Samples", "hole_name": "CBAC1-248", "alt_name": null, "drill_type": "Air core", "dg_drilltype": null, "mgan": null, "zone": null, "height": null, "confid_lith": null, "deviated": null, "openfile_dt": null, "titleref": null, "company": "Department Of Mineral Resources,", "plug_date": null, "mapsheet_100k": "Cobar", "colour": "red" }, "geometry": null },

Once all features with null geometries are removed, .fromGeoJSON works fine.

It would be better for .fromGeoJSON to discard null geometries and keep all others, or at least throw an error, so that users know what the problem is.  It took me a lot of trial and error to work out the cause of the failure!

**Comment by vfn** [comment]
@Tybion would you like to create a PR with the suggested improvements?

**Comment by Tybion** [comment]
What does that entail?

**Comment by Tybion** [comment]
This is a fantastic project, but I am totally bogged down with work at the moment, and this is my very first Swift app, so I just can't take this on.  I do contribute back to Open Source, but in areas where have experience.  Sorry.

**Comment by macdrevx** [comment]
Proposed version 5 supports Codable and is now up for review: #167

This may address some of your concerns about more helpful error messages. Please let me know if you have any feedback.

**Comment by macdrevx** [comment]
Version 5 now available.
