### ISSUE TITLE
GeoSwift equivalent on Android

### ISSUE THREAD

**Issue by WilliamMouline** [GEOSwift/GEOSwift#79]
Hi,

I would like to know if there is any progress on the Android library or if you know a solution on Android to use operations on geographical objects ?

Thanks.

**Comment by mojtabacazi** [comment]
@WilliamMouline Look at spatialite project for android.

**Comment by macdrevx** [comment]
@WilliamMouline check out https://github.com/locationtech/jts. It's actually the project that GEOS was based on.
