### ISSUE TITLE
Showing 340+ warnings in Swift 4 version

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [GEOSwift/GEOSwift#84]
Thanks for the great library. But, it is showing 340+ warnings in my xcode for Swift 4 version.
Can you make compatible if possible to Swift 4?

**Comment by vfn** [comment]
@AnilkumarRabhasa can you please post a screenshot or log?

**Comment by AnilkumarRabhasa** [comment]
PFA.
![screen shot 2018-03-20 at 8 51 16 pm](https://user-images.githubusercontent.com/8393997/37664078-9dfb2bf4-2c80-11e8-98cf-c78714d069ff.png)

![screen shot 2018-03-20 at 8 51 35 pm](https://user-images.githubusercontent.com/8393997/37664103-a6b70bd2-2c80-11e8-8998-3bc92e7574b8.png)

**Comment by vfn** [comment]
@AnilkumarRabhasa that's lib `geos` and not `GEOSwift`. https://github.com/OSGeo/geos.git
