### ISSUE TITLE
way to create GEOSwift with MKpolygon?

### ISSUE THREAD

**Issue by jwilson85** [GEOSwift/GEOSwift#87]
I would like to create a Geometry with an MKPolygon so that I can use the intersection method. Unless you know of a better way. I am trying to create a single polygon out of two intersecting polygons.

**Comment by vfn** [comment]
@jwilson85 could you please create a gist or add some code here?

**Comment by vfn** [comment]
You should be able to, you'll need to get the polygon points, as well as the points of inner polygons and then transform that into  a Polygon.

https://developer.apple.com/documentation/mapkit/mkpolygon
https://developer.apple.com/documentation/mapkit/mkmultipoint

**Comment by jwilson85** [comment]
Can you elaborate on the transferring into Polygon? I see it takes GEOGeom property. Which is typed as an opaque pointer. But I get lost in trying to figure out what that is.

**Comment by vfn** [comment]
@jwilson85 once you have the points from your `MKPolygon`, you can then instantiate a Polygon via `init?(shell: LinearRing, holes: Array<LinearRing>?)`

That's an example I run using the playground inside the project:

<img width="1101" alt="screen shot 2018-04-20 at 2 53 21 pm" src="https://user-images.githubusercontent.com/308592/39031299-aa499638-44aa-11e8-8f3a-c8c1bb9a4fc0.png">

I didn't handle the interior rings tho.

And the code:

```Swift
let p1 = Geometry.create("POLYGON((35 10, 45 45.5, 15 40, 10 20, 35 10),(20 30, 35 35, 30 20, 20 30))")

let mkp = p1?.mapShape() as! MKPolygon

var coords: [CLLocationCoordinate2D] = (0 ..< mkp.pointCount)
    .compactMap({
        var c = kCLLocationCoordinate2DInvalid
        mkp.getCoordinates(&c, range: NSRange(location: $0, length: 1))
        return c
    })

let shellPoints = coords.map({ Coordinate(x: $0.longitude, y: $0.latitude) })
let shell = LinearRing(points: shellPoints)!
Polygon(shell: shell, holes: nil)
```

**Comment by jwilson85** [comment]
I see that gives me enough info to turn an MKPolygon into a Polygon TY
