### ISSUE TITLE
Swift 4 and GEOSwift compile warnings

### ISSUE THREAD

**Issue by sbrioux** [GEOSwift/GEOSwift#89]
Currently in my application i'm seeing ~ 354 total warnings from the GEOSwift library.  Is there any plan to update to fix these warnings?

**Comment by macdrevx** [comment]
@sbrioux not sure of the plans, and I too would like to see them fixed. If you want to use the library anyway in the meantime but silence the warnings (and if you're using CocoaPods) you can ignore them using `pod 'GEOSwift', inhibit_warnings: true` in your Podfile.

**Comment by vfn** [comment]
@sbrioux can you please provide more information? A screenshot would help.

Thanks!

**Comment by sbrioux** [comment]
Looks like just 6 issues from the GEOSwift library but 356 from the geos library

<img width="271" alt="screen shot 2018-05-03 at 9 39 00 am" src="https://user-images.githubusercontent.com/4192331/39579897-d942a000-4eb5-11e8-8eb3-3133dae35f21.png">

**Comment by vfn** [comment]
@sbrioux it would be great if you could create a pull request, and fix these 6 warnings.

To silence the remaining ones from`geos` use @macdrevx 's suggestion.

**Comment by macdrevx** [comment]
Looks like this is fixed in develop. Thanks @sbrioux and @simonbilskyrollins.
